/**
 * Table des archétypes d'ennemis - un seul fichier à modifier pour
 * ajouter un nouveau type de combat (un gobelin rapide et fragile, un
 * squelette lent et résistant...) sans toucher au reste du système.
 *
 * Chaque archétype suit la MÊME formule de mise à l'échelle par
 * profondeur (croissance exponentielle sur hp/dégâts/xp, additive et
 * plafonnée sur vitesse/défense - cf. le détail dans getEnemyStatsForDepth)
 * mais avec ses PROPRES constantes de base et de croissance. La courbe
 * elle-même (le "pourquoi" de cette forme) est expliquée une seule fois
 * ici plutôt que répétée par archétype.
 *
 * Volontairement calculé côté serveur : les stats déterminent l'issue des
 * combats, donc c'est la même logique de confiance que la génération de
 * niveau - le client ne doit jamais pouvoir se donner ses propres stats.
 * Pour la même raison, c'est aussi le serveur qui CHOISIT quel archétype
 * un ennemi donné utilise (cf. ArpgController.getLevel) - le client se
 * contente d'afficher le sprite correspondant au type reçu, il ne tire
 * jamais ce choix de son côté (ça désynchroniserait visuel et stats).
 */

const ENEMY_TYPES = {
  enemyDefault: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    // >1 = croissance exponentielle. Volontairement différencié par stat :
    // les PV grimpent un peu plus vite que les dégâts, pour que les
    // combats s'allongent en profondeur plutôt que de devenir
    // immédiatement mortels des deux côtés à la fois.
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    // vitesse et défense évoluent à part, en additif et plafonné - une
    // croissance exponentielle sur ces deux stats rendrait les ennemis
    // injouables (intouchables ou infuyables) bien avant que PV/dégâts
    // n'atteignent des niveaux critiques
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3, // +1 defense tous les 3 etages
  },
  goblin: {
    base: { hp: 10, damage: 3, xpReward: 8 },
    growthRate: { hp: 1.15, damage: 1.12, xpReward: 1.1 },
    speedBase: 100,
    speedMax: 160,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  goblin2: {
    base: { hp: 12, damage: 2, xpReward: 9 },
    growthRate: { hp: 1.14, damage: 1.11, xpReward: 1.09 },
    speedBase: 110,
    speedMax: 170,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  monks1: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  monks2: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  monks3: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  monks4: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  elementalfairy1: {
    attackType: "ranged",
    base: { hp: 10, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  elementalfairy2: {
    attackType: "ranged",
    base: { hp: 10, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  elementalfairy3: {
    attackType: "ranged",
    base: { hp: 10, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  elementalfairy4: {
    attackType: "ranged",
    base: { hp: 10, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  fairy1: {
    attackType: "ranged",
    base: { hp: 10, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  fairy2: {
    attackType: "ranged",
    base: { hp: 10, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  fairy3: {
    attackType: "ranged",
    base: { hp: 10, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  fairy4: {
    attackType: "ranged",
    base: { hp: 10, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat1: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat2: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat3: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat4: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat5: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat6: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat7: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  colorBat8: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  brownMushroom: {
    base: { hp: 10, damage: 3, xpReward: 8 },
    growthRate: { hp: 1.15, damage: 1.12, xpReward: 1.1 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  angryBrownMushroom: {
    base: { hp: 12, damage: 4, xpReward: 9 },
    growthRate: { hp: 1.16, damage: 1.13, xpReward: 1.11 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  redMushroom: {
    base: { hp: 14, damage: 5, xpReward: 11 },
    growthRate: { hp: 1.17, damage: 1.14, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  angryRedMushroom: {
    base: { hp: 16, damage: 6, xpReward: 12 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  angryStump: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  armsAngryStumps: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  redEarthworms: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  blackBug: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady1: {
    base: { hp: 12, damage: 4, xpReward: 1 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.1 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady2: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady3: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady4: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady5: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady6: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady7: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  demonLady8: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  gazer1: {
    base: { hp: 12, damage: 4, xpReward: 1 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.1 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  gazer2: {
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  gazer3: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  gazer4: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  gazer5: {
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  // soldier1 to soldier 16 with the same stats as monks1
  soldier1: {
    attackType: "ranged",
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier2: {
    attackType: "ranged",
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier3: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier4: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier5: {
    attackType: "ranged",
    base: { hp: 28, damage: 8, xpReward: 18 },
    growthRate: { hp: 1.22, damage: 1.19, xpReward: 1.16 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier6: {
    attackType: "ranged",
    base: { hp: 30, damage: 9, xpReward: 20 },
    growthRate: { hp: 1.23, damage: 1.2, xpReward: 1.17 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier7: {
    base: { hp: 32, damage: 10, xpReward: 22 },
    growthRate: { hp: 1.24, damage: 1.21, xpReward: 1.18 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier8: {
    base: { hp: 34, damage: 11, xpReward: 24 },
    growthRate: { hp: 1.25, damage: 1.22, xpReward: 1.19 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier9: {
    attackType: "ranged",
    base: { hp: 20, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier10: {
    attackType: "ranged",
    base: { hp: 22, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier11: {
    base: { hp: 24, damage: 6, xpReward: 14 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.14 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier12: {
    base: { hp: 26, damage: 7, xpReward: 16 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.15 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier13: {
    attackType: "ranged",
    base: { hp: 28, damage: 8, xpReward: 18 },
    growthRate: { hp: 1.22, damage: 1.19, xpReward: 1.16 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier14: {
    attackType: "ranged",
    base: { hp: 30, damage: 9, xpReward: 20 },
    growthRate: { hp: 1.23, damage: 1.2, xpReward: 1.17 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier15: {
    base: { hp: 32, damage: 10, xpReward: 22 },
    growthRate: { hp: 1.24, damage: 1.21, xpReward: 1.18 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  soldier16: {
    base: { hp: 34, damage: 11, xpReward: 24 },
    growthRate: { hp: 1.25, damage: 1.22, xpReward: 1.19 },
    speedBase: 90,
    speedMax: 140,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  enemy1: {
    base: { hp: 34, damage: 6, xpReward: 15 },
    growthRate: { hp: 1.2, damage: 1.18, xpReward: 1.15 },
    speedBase: 80,
    speedMax: 130,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  // manquait jusqu'ici (utilise dans biomeConfig.js sans jamais avoir ete
  // defini ici - retombait silencieusement sur enemyDefault, trouve en
  // verifiant la coherence entre les deux fichiers). Meme famille que
  // enemy1 (courbe de croissance proche), legerement au-dessus en base
  // pour rester la deuxieme variante du temple.
  enemy2: {
    base: { hp: 41, damage: 8, xpReward: 21 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.13 },
    speedBase: 80,
    speedMax: 130,
    speedGrowthPerDepth: 2,
    defenseGrowthEveryNDepths: 3,
  },
  bat1: {
    base: { hp: 10, damage: 2, xpReward: 1 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  bat1a: {
    base: { hp: 12, damage: 2, xpReward: 2 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  bee1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },

  bird1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  bug1a: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  bug1b: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  cockatrice1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  deer1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  deer2: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  fox1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  fox2: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  lizard: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  raccoon1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  slime1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  kobold1: {
    base: { hp: 32, damage: 6, xpReward: 15 },
    growthRate: { hp: 1.16, damage: 1.13, xpReward: 1.11 },
    speedBase: 95,
    speedMax: 150,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  kobold2: {
    base: { hp: 32, damage: 6, xpReward: 15 },
    growthRate: { hp: 1.17, damage: 1.14, xpReward: 1.12 },
    speedBase: 90,
    speedMax: 145,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  kobold3: {
    base: { hp: 32, damage: 6, xpReward: 15 },
    growthRate: { hp: 1.18, damage: 1.15, xpReward: 1.13 },
    speedBase: 85,
    speedMax: 140,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  naga1: {
    attackType: "ranged",
    base: { hp: 23, damage: 5, xpReward: 11 },
    growthRate: { hp: 1.19, damage: 1.16, xpReward: 1.14 },
    speedBase: 80,
    speedMax: 135,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  naga2: {
    attackType: "ranged",
    base: { hp: 24, damage: 5, xpReward: 11 },
    growthRate: { hp: 1.2, damage: 1.17, xpReward: 1.15 },
    speedBase: 75,
    speedMax: 130,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  naga3: {
    attackType: "ranged",
    base: { hp: 25, damage: 5, xpReward: 12 },
    growthRate: { hp: 1.21, damage: 1.18, xpReward: 1.16 },
    speedBase: 70,
    speedMax: 125,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  naga4: {
    attackType: "ranged",
    base: { hp: 32, damage: 9, xpReward: 16 },
    growthRate: { hp: 1.22, damage: 1.19, xpReward: 1.17 },
    speedBase: 65,
    speedMax: 120,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  naga5: {
    attackType: "ranged",
    base: { hp: 22, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.23, damage: 1.2, xpReward: 1.18 },
    speedBase: 60,
    speedMax: 115,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },

  naga6: {
    attackType: "ranged",
    base: { hp: 22, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.24, damage: 1.21, xpReward: 1.19 },
    speedBase: 55,
    speedMax: 110,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  naga7: {
    attackType: "ranged",
    base: { hp: 21, damage: 4, xpReward: 10 },
    growthRate: { hp: 1.25, damage: 1.22, xpReward: 1.2 },
    speedBase: 50,
    speedMax: 105,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc1: {
    base: { hp: 16, damage: 3, xpReward: 8 },
    growthRate: { hp: 1.26, damage: 1.23, xpReward: 1.21 },
    speedBase: 45,
    speedMax: 100,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc2: {
    base: { hp: 18, damage: 4, xpReward: 9 },
    growthRate: { hp: 1.27, damage: 1.24, xpReward: 1.22 },
    speedBase: 40,
    speedMax: 95,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },

  orc3: {
    base: { hp: 19, damage: 4, xpReward: 9 },
    growthRate: { hp: 1.28, damage: 1.25, xpReward: 1.23 },
    speedBase: 35,
    speedMax: 90,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc4: {
    base: { hp: 14, damage: 3, xpReward: 6 },
    growthRate: { hp: 1.29, damage: 1.26, xpReward: 1.24 },
    speedBase: 30,
    speedMax: 85,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc5: {
    base: { hp: 13, damage: 3, xpReward: 6 },
    growthRate: { hp: 1.3, damage: 1.27, xpReward: 1.25 },
    speedBase: 25,
    speedMax: 80,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc6: {
    base: { hp: 13, damage: 2, xpReward: 5 },
    growthRate: { hp: 1.31, damage: 1.28, xpReward: 1.26 },
    speedBase: 20,
    speedMax: 75,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc7: {
    base: { hp: 9, damage: 2, xpReward: 4 },
    growthRate: { hp: 1.32, damage: 1.29, xpReward: 1.27 },
    speedBase: 15,
    speedMax: 70,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  orc8: {
    base: { hp: 9, damage: 2, xpReward: 4 },
    growthRate: { hp: 1.33, damage: 1.3, xpReward: 1.28 },
    speedBase: 10,
    speedMax: 65,
    speedGrowthPerDepth: 3,
    defenseGrowthEveryNDepths: 4,
  },
  lamia1: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  lamia2: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  lamia3: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  lamia4: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  lamia5: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  lamia6: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 1 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  vampire1: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 1 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  vampire2: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  vampire3: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  vampire4: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  vampire5: {
    attackType: "ranged",
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },

  maxibee1: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  BigBug: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
  GiantFox: {
    base: { hp: 8, damage: 2, xpReward: 7 },
    growthRate: { hp: 1.13, damage: 1.1, xpReward: 1.08 },
    speedBase: 120,
    speedMax: 180,
    speedGrowthPerDepth: 4,
    defenseGrowthEveryNDepths: 5,
  },
};

/**
 * @param {number} depth profondeur (1 = premier étage)
 * @param {string} [typeKey='enemyDefault'] clé d'archétype (cf. ENEMY_TYPES)
 * @returns {{hp:number, damage:number, defense:number, speed:number, xpReward:number}}
 */
function getEnemyStatsForDepth(depth, typeKey = "enemyDefault") {
  if (depth < 1) {
    throw new Error("getEnemyStatsForDepth: depth doit être >= 1");
  }

  const type = ENEMY_TYPES[typeKey] || ENEMY_TYPES.enemyDefault;
  const n = depth - 1; // pas de croissance au premier etage (stats de base pures)

  return {
    hp: Math.round(type.base.hp * Math.pow(type.growthRate.hp, n)),
    damage: Math.round(type.base.damage * Math.pow(type.growthRate.damage, n)),
    xpReward: Math.round(
      type.base.xpReward * Math.pow(type.growthRate.xpReward, n),
    ),
    defense: Math.floor(n / type.defenseGrowthEveryNDepths),
    speed: Math.min(
      type.speedMax,
      type.speedBase + n * type.speedGrowthPerDepth,
    ),
    // 'melee' par defaut (comportement inchange pour tout type qui ne
    // definit pas ce champ) - 'ranged' pour les types qui doivent
    // attaquer a distance plutot qu'au contact (cf. les nagas,
    // MainScene.updateEnemyAttacks/updateEnemyProjectiles cote client)
    attackType: type.attackType || "melee",
  };
}

module.exports = { getEnemyStatsForDepth, ENEMY_TYPES };
