/**
 * Table des competences/pouvoirs - meme esprit qu'itemDefs.js (une
 * table statique, resolveAbilityDef gere le repli si une competence
 * cote serveur n'est pas encore connue du client).
 *
 * `archetype` : specifique a un heros (cf. HERO_STATS_PROFILES) - jamais
 * utilisable par un autre archetype, meme trouvee/achetee.
 *
 * `unlockLevel` : si defini, debloquee AUTOMATIQUEMENT des que le joueur
 * (du bon archetype) atteint ce niveau - cf. MainScene.checkLevelUp.
 * Absent/null = ne se debloque jamais toute seule, doit etre obtenue
 * autrement (loot, achat en boutique - representee comme un objet
 * "parchemin" dans l'inventaire, cf. itemDefs.js/category 'abilityScroll').
 *
 * `effectType` : 'aoe' (degats en zone, IMPLEMENTE), 'pierce' (transperce
 * plusieurs ennemis alignes, a construire), 'debuff' (ralentit/affaiblit
 * temporairement un ennemi, a construire), 'buff' (ameliore
 * temporairement une stat du heros, a construire) - les 3 derniers
 * reutiliseront le systeme de statusEffects deja construit pour
 * saignement/brulure, etendu pour porter des modificateurs de stat en
 * plus des degats par tic.
 */
export const ABILITY_DEFS = {
  // base abilities
  fireball: {
    id: "fireball",
    name: "Boule de feu",
    archetypes: [],
    description:
      "Projectile qui explose en zone au contact d'un ennemi (18 degats). 15 mana.",
    manaCost: 15,
    cooldownMs: 3000,
    effectType: "projectileAoe", // voyage comme un projectile, explose au contact - distinct de 'aoe' (instantane, centre sur le heros)
    damage: 18, // degats a TOUS les ennemis dans le rayon de l'EXPLOSION, pas juste celui touche en premier
    damagePercent: 0.7,
    scalesFrom: "ranged",
    radius: 70, // rayon de l'explosion au point d'impact
    projectileSpeed: 260,
    maxDistance: 400, // disparait sans exploser s'il ne touche rien avant cette distance
    unlockLevel: 1,
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      damageType: "fire",
      kind: "dot",
      chance: 0.3,
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
  },
  whirlwind: {
    id: "whirlwind",
    name: "Tourbillon",
    archetypes: ["guerrier", "archer"],
    description:
      "Frappe tous les ennemis a portee de melee (14 degats). 20 stamina.",
    staminaCost: 20,
    cooldownMs: 4000,
    effectType: "aoe",
    damage: 14,
    damagePercent: 0.6,
    scalesFrom: "melee",
    radius: 55, // proche de playerMeleeRange - degats tout autour, contrairement au cone normal de l'attaque de base
    unlockLevel: 3,
  },

  haste: {
    id: "haste",
    name: "Hâte",
    archetypes: ["guerrier", "archer"], // utilisable par tous - restreins si tu veux la limiter
    description:
      "Augmente ta vitesse de déplacement pendant un court moment. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "selfBuff",
    statModifiers: { moveSpeedPercent: 0.6 },
    durationMs: 4000,
    unlockLevel: 3, // a debloquer via parchemin/loot pour l'instant
  },
  slow: {
    id: "slow",
    name: "Ralentissement",
    archetypes: ["mage", "archer"],
    description: "Ralentit tous les ennemis à portée de mêlée. 15 mana.",
    manaCost: 15,
    cooldownMs: 6000,
    effectType: "aoeDebuff",
    radius: 55,
    statModifiers: { moveSpeedPercent: -0.5 },
    durationMs: 3000,
    unlockLevel: 2,
  },
  piercingArrow: {
    id: "piercingArrow",
    name: "Flèche perforante",
    archetypes: ["archer", "voleur"],
    description:
      "Tire une flèche qui transperce plusieurs ennemis alignés (14 degats). 15 stamina.",
    staminaCost: 15,
    cooldownMs: 3500,
    effectType: "pierce",
    damage: 14,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    projectileSpeed: 380,
    maxDistance: 450,
    maxPierceCount: 3, // touche au plus 3 ennemis avant de disparaitre - optionnel, absent = infini (transperce jusqu'a maxDistance)
    unlockLevel: 1,
  },
  flameWeapon: {
    id: "flameWeapon",
    name: "Lame enflammée",
    archetypes: ["guerrier"],
    description:
      "Le prochain coup porté inflige des dégâts supplémentaires (+10) et une forte chance de brûlure. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 5000,
    effectType: "weaponImbue",
    bonusDamage: 10,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.8, // haute expres - c'est un coup DELIBEREMENT enchante, pas le taux passif habituel d'une arme
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 5,
  },
  fireWall: {
    id: "fireWall",
    name: "Mur de flammes",
    archetypes: ["mage"],
    description:
      "Crée un mur de flammes qui inflige des dégâts sur la durée aux ennemis qui le traversent (20 dégâts). 20 mana.",
    manaCost: 20,
    cooldownMs: 8000,
    effectType: "aoe",
    damage: 20,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "fire",
    radius: 80,
    durationMs: 5000,
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.8, // haute expres - c'est un coup DELIBEREMENT enchante, pas le taux passif habituel d'une arme
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 1,
  },
  scoutPulse: {
    id: "scoutPulse",
    name: "Pulsation d'exploration",
    archetypes: [],
    description:
      "Révèle une large zone du brouillard de guerre autour de toi. 1 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "fogPulse",
    radius: 10, // en CASES (coordonnees de tuiles), pas en pixels - different des autres competences
    ignoresWalls: true,
    disabledBiomes: ["maze1", "maze2"], // ids de biomeConfig.js - absent/vide = utilisable partout
    unlockLevel: null,
  },
  shieldBash: {
    id: "shieldBash",
    name: "Coup de bouclier",
    archetypes: ["guerrier"],
    description:
      "Fonce en ligne droite, percute et repousse les ennemis sur le passage. Nécessite un bouclier équipé. 20 stamina.",
    staminaCost: 20,
    cooldownMs: 6000,
    effectType: "shieldBash",
    requiresShield: true,
    damage: 16,
    damagePercent: 0.6,
    scalesFrom: "melee",
    dashDistance: 150, // en pixels
    dashSpeed: 500,
    knockbackDistance: 40,
    unlockLevel: null,
  },
  taunt: {
    id: "taunt",
    name: "Cri de défi",
    archetypes: ["guerrier"],
    description: "Attire l'attention de tous les ennemis proches. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 10000,
    effectType: "taunt",
    radius: 150, // en pixels, comme les autres AoE
    unlockLevel: null,
  },
  repel: {
    id: "repel",
    name: "Répulsion",
    archetypes: [],
    description: "Repousse tous les ennemis proches. 15 mana.",
    manaCost: 15,
    cooldownMs: 8000,
    effectType: "repel",
    radius: 100,
    knockbackDistance: 80,
    damage: 0, // optionnel - laisse a 0 si tu veux un pur effet de recul, sans degats
    unlockLevel: null,
  },
  stun: {
    id: "stun",
    name: "Étourdissement",
    archetypes: [],
    description:
      "Étourdit tous les ennemis proches, les empêchant d'agir un court moment. 20 mana.",
    manaCost: 20,
    cooldownMs: 10000,
    effectType: "aoeStun",
    radius: 90,
    durationMs: 2500,
    unlockLevel: null,
  },
  summonAlly: {
    id: "summonAlly",
    name: "Invocation",
    archetypes: ["mage"],
    description:
      "Invoque un allié temporaire qui combat à tes côtés, jusqu'à sa mort ou expiration. 30 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "summon",
    summonType: "gazer1", // cle SPRITE_REGISTRY a utiliser pour le visuel - a remplacer par un sprite plus adapte si tu en as un
    durationMs: null, // null = dure jusqu'a la mort uniquement, jamais d'expiration
    hp: 40,
    damage: 8,
    defense: 1,
    damageType: "fire",
    resistances: { fire: 1 },
    unlockLevel: null,
  },
  summonAlly2: {
    id: "summonAlly2",
    name: "Invocation 2",
    archetypes: ["mage"],
    description:
      "Invoque un allié temporaire qui combat à tes côtés, jusqu'à sa mort ou expiration. 30 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "summon",
    summonType: "gazer2", // cle SPRITE_REGISTRY a utiliser pour le visuel - a remplacer par un sprite plus adapte si tu en as un
    durationMs: null, // null = dure jusqu'a la mort uniquement, jamais d'expiration
    hp: 40,
    damage: 8,
    defense: 1,
    damageType: "physical",
    resistances: { physical: 1 },
    unlockLevel: null,
  },
  summonWolf: {
    id: "summonWolf",
    name: "Invocation : Loup",
    archetypes: ["voleur"],
    description: "Invoque un loup rapide mais fragile. 25 stamina.",
    staminaCost: 25,
    cooldownMs: 18000,
    effectType: "summon",
    summonType: "enemyDefault", // remplace par un sprite dedie si tu en as un
    durationMs: 15000,
    hp: 25,
    damage: 12,
    defense: 0,
    damageType: "physical",
  },

  summonIceElemental: {
    id: "summonIceElemental",
    name: "Invocation : Élémentaire de glace",
    archetypes: ["mage"],
    description:
      "Invoque un élémentaire robuste et résistant au froid. 35 mana.",
    manaCost: 35,
    cooldownMs: 25000,
    effectType: "summon",
    summonType: "enemyDefault",
    durationMs: 25000,
    hp: 60,
    damage: 6,
    defense: 3,
    damageType: "cold",
    resistances: { cold: 1, fire: -0.5 },
  },
  summonFamiliar: {
    id: "summonFamiliar",
    name: "Familier",
    archetypes: ["mage"],
    description:
      "Invoque un familier qui te suit d'étage en étage, jusqu'à sa mort. 40 mana.",
    manaCost: 1,
    cooldownMs: 30000,
    effectType: "summon",
    summonType: "wolfFamiliar",
    durationMs: null, // jamais d'expiration par duree - uniquement la mort le fait disparaitre
    hpScale: 0.5,
    damageScale: 0.6,
    defenseScale: 0.5,
    damageType: "physical",
    persistent: true,
  },
  shortDash: {
    id: "shortDash",
    name: "Ruée",
    archetypes: [],
    description: "Téléportation courte dans la direction actuelle. 10 stamina.",
    staminaCost: 10,
    cooldownMs: 4000,
    effectType: "teleportDash",
    distance: 120,
  },
  randomTeleport: {
    id: "randomTeleport",
    name: "Téléportation aléatoire",
    archetypes: [],
    description: "Téléporte vers un point aléatoire de l'étage. 20 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "randomTeleport",
  },
  stealth: {
    id: "stealth",
    name: "Furtivité",
    archetypes: ["voleur"],
    description: "Devient indétectable un court moment. 5 stamina.",
    staminaCost: 5,
    cooldownMs: 8000,
    effectType: "stealth",
    durationMs: 5000,
  },
  chainLightning: {
    id: "chainLightning",
    name: "Éclair en chaîne",
    archetypes: ["mage"],
    description:
      "Frappe un ennemi puis rebondit vers les plus proches. 25 mana.",
    manaCost: 1,
    cooldownMs: 7000,
    effectType: "chainLightning",
    damage: 14,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "electricity",
    maxJumps: 4,
    jumpRange: 150,
  },
  toxicCloud: {
    id: "toxicCloud",
    name: "Nuage toxique",
    archetypes: ["mage"],
    description: "Zone toxique persistante. 25 mana.",
    manaCost: 1,
    cooldownMs: 12000,
    effectType: "zone",
    radius: 70,
    durationMs: 6000,
    tickIntervalMs: 1000,
    damagePerTick: 4,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "poison",
    color: 0x66cc44,
  },
  firePool: {
    id: "firePool",
    name: "Mare de feu",
    archetypes: ["mage"],
    description: "Zone de feu persistante. 25 mana.",
    manaCost: 1,
    cooldownMs: 12000,
    effectType: "zone",
    radius: 70,
    durationMs: 6000,
    tickIntervalMs: 800,
    damagePerTick: 5,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "fire",
    color: 0xff6600,
  },
  curse: {
    id: "curse",
    name: "Malédiction",
    archetypes: ["mage"],
    description: "Réduit les dégâts infligés par les ennemis proches. 20 mana.",
    manaCost: 1,
    cooldownMs: 12000,
    effectType: "aoeCurse",
    radius: 100,
    durationMs: 6000,
    damagePercent: -0.4,
  },
  vampiricStrike: {
    id: "vampiricStrike",
    name: "Frappe vampirique",
    archetypes: ["voleur"],
    description:
      "Le prochain coup soigne un % des dégâts infligés. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "weaponImbue",
    healPercent: 0.5,
  },
  riposte: {
    id: "riposte",
    name: "Riposte",
    archetypes: ["guerrier"],
    description:
      "Renvoie une partie des dégâts subis un court moment. 20 stamina.",
    staminaCost: 20,
    cooldownMs: 10000,
    effectType: "riposte",
    durationMs: 4000,
    reflectPercent: 0.5,
  },
  parry: {
    id: "parry",
    name: "Parade",
    archetypes: ["guerrier"],
    description:
      "Réduit fortement les dégâts subis un court instant. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "parry",
    durationMs: 1500,
    damageReduction: 0.8,
  },
  poisonTrap: {
    id: "poisonTrap",
    name: "Piège empoisonné",
    archetypes: ["voleur"],
    description: "Pose un piège qui empoisonne au contact. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "trap",
    damageType: "poison",
    inflictsEffect: {
      type: "poison",
      kind: "dot",
      chance: 1,
      damagePerTick: 3,
      damagePercent: 0.6,
      scalesFrom: "ranged",
      tickIntervalMs: 1000,
      ticks: 4,
    },
    triggerRadius: 20,
    expiresAfterMs: 30000,
  },
  fireTrap: {
    id: "fireTrap",
    name: "Piège incendiaire",
    archetypes: ["voleur"],
    description: "Pose un piège qui enflamme au contact. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "trap",
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 1,
      damagePerTick: 4,
      damagePercent: 0.6,
      scalesFrom: "ranged",
      tickIntervalMs: 1000,
      ticks: 3,
    },
    triggerRadius: 20,
    expiresAfterMs: 30000,
  },
  bleedTrap: {
    id: "bleedTrap",
    name: "Piège lacérant",
    archetypes: ["voleur"],
    description: "Pose un piège qui lacère au contact. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "trap",
    inflictsEffect: {
      type: "bleed",
      kind: "dot",
      chance: 1,
      damagePerTick: 3,
      damagePercent: 0.6,
      scalesFrom: "ranged",
      tickIntervalMs: 800,
      ticks: 5,
    },
    triggerRadius: 20,
    expiresAfterMs: 30000,
  },
  freeze: {
    id: "freeze",
    name: "Gel",
    archetypes: ["mage"],
    description: "Projectile qui explose et gèle les ennemis touchés. 18 mana.",
    manaCost: 1,
    cooldownMs: 10, //5000
    effectType: "projectileAoe",
    damage: 10,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "cold",
    radius: 60,
    projectileSpeed: 260,
    maxDistance: 400,
    inflictsEffect: {
      type: "stun",
      kind: "modifier",
      chance: 0.6,
      statModifiers: {},
      durationMs: 1500,
    },
  },
  frozenWall: {
    id: "frozenWall",
    name: "Mur de givre",
    archetypes: ["mage"],
    description:
      "Vague de froid en cône qui ralentit sur son passage. 25 mana.",
    manaCost: 1,
    cooldownMs: 10000,
    effectType: "cone",
    distance: 180,
    angleDegrees: 60,
    damage: 8,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "cold",
    inflictsEffect: {
      type: "slow",
      kind: "modifier",
      chance: 1,
      statModifiers: { moveSpeedPercent: -0.5 },
      durationMs: 3000,
    },
  },
  root: {
    id: "root",
    name: "Racines",
    archetypes: ["mage"],
    description:
      "Bloque le mouvement des ennemis proches (ils peuvent encore attaquer). 18 mana.",
    manaCost: 1,
    cooldownMs: 9000,
    effectType: "aoeRoot",
    radius: 90,
    durationMs: 3000,
  },
  boomerangAxe: {
    id: "boomerangAxe",
    name: "Hache boomerang",
    archetypes: ["guerrier"],
    description: "Lance une hache qui revient après son trajet. 18 stamina.",
    staminaCost: 18,
    cooldownMs: 6000,
    effectType: "boomerang",
    damage: 12,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    projectileSpeed: 300,
    maxDistance: 250,
  },
  vortex: {
    id: "vortex",
    name: "Vortex",
    archetypes: ["mage"],
    description: "Attire tous les ennemis proches vers toi. 20 mana.",
    manaCost: 1,
    cooldownMs: 10000,
    effectType: "vortex",
    radius: 150,
    pullDistance: 80,
  },
  execute: {
    id: "execute",
    name: "Exécution",
    archetypes: [],
    description:
      "Le prochain coup inflige des dégâts massifs si la cible est sous 25% de PV. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "weaponImbue",
    executeThreshold: 0.25,
    executeBonusMultiplier: 3,
  },
  extendedVision: {
    id: "extendedVision",
    name: "Vision perçante",
    archetypes: [],
    description: "Augmente ta portée de vue un moment. 15 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "visionBuff",
    visionBonus: 4,
    durationMs: 10000,
  },
  bloodPact: {
    id: "bloodPact",
    name: "Pacte de sang",
    archetypes: ["mage"],
    description: "Convertit des PV en mana instantanément.",
    cooldownMs: 15000,
    effectType: "bloodPact",
    hpCost: 20,
    resourceGain: 30,
    resourceType: "mana",
  },
  berserker: {
    id: "berserker",
    name: "Rage berserker",
    archetypes: ["guerrier"],
    description:
      "Sous 30% de PV : +80% dégâts, -30% défense un moment. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 15000,
    effectType: "conditionalBuff",
    hpThresholdPercent: 0.3,
    durationMs: 6000,
    buffStatModifiers: {
      meleeDamagePercent: 0.8,
      rangedDamagePercent: 0.8,
      defensePercent: -0.3,
    },
  },
  recklessRage: {
    id: "recklessRage",
    name: "Rage à double tranchant",
    archetypes: ["guerrier"],
    description: "+50% dégâts, -25% défense, sans condition. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 10000,
    effectType: "selfBuff",
    durationMs: 6000,
    buffStatModifiers: {
      meleeDamagePercent: 0.5,
      rangedDamagePercent: 0.5,
      defensePercent: -0.25,
    },
  },
};

/**
 * Resout la definition d'une competence par son id - repli generique si
 * elle n'est pas (encore) connue du client, meme principe que
 * resolveItemDef.
 */
export function resolveAbilityDef(abilityId) {
  return (
    ABILITY_DEFS[abilityId] || {
      id: abilityId,
      name: abilityId,
      archetypes: [],
      staminaCost: 10,
      cooldownMs: 2000,
      effectType: "aoe",
      damage: 5,
      radius: 50,
      unlockLevel: null,
    }
  );
}
