/**
 * Table des competences/pouvoirs - meme esprit qu'itemDefs.js (une
 * table statique, resolveAbilityDef gere le repli si une competence
 * cote serveur n'est pas encore connue du client).
 *
 * `archetype` : specifique a un heros (cf. HERO_STATS_PROFILES) - jamais
 * utilisable par un autre archetype, meme trouvee/achetee.
 *
 * `unlockLevel` : si defini, debloquee AUTOMATIQUEMENT des que le joueur
 * (du bon archetype) atteint ce niveau - cf. MainScene.checkLevelUp.
 * Absent/null = ne se debloque jamais toute seule, doit etre obtenue
 * autrement (loot, achat en boutique - representee comme un objet
 * "parchemin" dans l'inventaire, cf. itemDefs.js/category 'abilityScroll').
 *
 * `effectType` : 'aoe' (degats en zone, IMPLEMENTE), 'pierce' (transperce
 * plusieurs ennemis alignes, a construire), 'debuff' (ralentit/affaiblit
 * temporairement un ennemi, a construire), 'buff' (ameliore
 * temporairement une stat du heros, a construire) - les 3 derniers
 * reutiliseront le systeme de statusEffects deja construit pour
 * saignement/brulure, etendu pour porter des modificateurs de stat en
 * plus des degats par tic.
 */
export const ABILITY_DEFS = {
  // base abilities
  fireball: {
    id: "fireball",
    name: "Boule de feu",
    archetypes: [],
    description:
      "Projectile qui explose en zone au contact d'un ennemi (18 degats). 15 mana.",
    manaCost: 15,
    cooldownMs: 3000,
    effectType: "projectileAoe", // voyage comme un projectile, explose au contact - distinct de 'aoe' (instantane, centre sur le heros)
    damage: 18, // degats a TOUS les ennemis dans le rayon de l'EXPLOSION, pas juste celui touche en premier
    damagePercent: 0.7,
    scalesFrom: "ranged",
    radius: 70, // rayon de l'explosion au point d'impact
    projectileSpeed: 260,
    maxDistance: 400, // disparait sans exploser s'il ne touche rien avant cette distance
    unlockLevel: 1,
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      damageType: "fire",
      kind: "dot",
      chance: 0.3,
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
  },
  whirlwind: {
    id: "whirlwind",
    name: "Tourbillon",
    archetypes: ["guerrier", "archer"],
    description:
      "Frappe tous les ennemis a portee de melee (14 degats). 20 stamina.",
    staminaCost: 20,
    cooldownMs: 4000,
    effectType: "aoe",
    damage: 14,
    damagePercent: 0.6,
    scalesFrom: "melee",
    radius: 55, // proche de playerMeleeRange - degats tout autour, contrairement au cone normal de l'attaque de base
    unlockLevel: 3,
  },

  haste: {
    id: "haste",
    name: "Hâte",
    archetypes: ["guerrier", "archer"], // utilisable par tous - restreins si tu veux la limiter
    description:
      "Augmente ta vitesse de déplacement pendant un court moment. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "selfBuff",
    statModifiers: { moveSpeedPercent: 0.6 },
    durationMs: 4000,
    unlockLevel: 3, // a debloquer via parchemin/loot pour l'instant
  },
  slow: {
    id: "slow",
    name: "Ralentissement",
    archetypes: ["mage", "archer"],
    description: "Ralentit tous les ennemis à portée de mêlée. 15 mana.",
    manaCost: 15,
    cooldownMs: 6000,
    effectType: "aoeDebuff",
    radius: 55,
    statModifiers: { moveSpeedPercent: -0.5 },
    durationMs: 3000,
    unlockLevel: 2,
  },
  piercingArrow: {
    id: "piercingArrow",
    name: "Flèche perforante",
    archetypes: ["archer", "voleur"],
    description:
      "Tire une flèche qui transperce plusieurs ennemis alignés (14 degats + 60% de tes degats d'attaque). 15 stamina.",
    staminaCost: 15,
    cooldownMs: 3500,
    effectType: "pierce",
    damage: 14,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    projectileSpeed: 380,
    maxDistance: 450,
    maxPierceCount: 3, // touche au plus 3 ennemis avant de disparaitre - optionnel, absent = infini (transperce jusqu'a maxDistance)
    unlockLevel: 1,
  },
  flameWeapon: {
    id: "flameWeapon",
    name: "Lame enflammée",
    archetypes: ["guerrier"],
    description:
      "Le prochain coup porté inflige des dégâts supplémentaires (+10) et une forte chance de brûlure. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 5000,
    effectType: "weaponImbue",
    bonusDamage: 10,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.8, // haute expres - c'est un coup DELIBEREMENT enchante, pas le taux passif habituel d'une arme
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 5,
  },
  flamingEdge: {
    id: "flamingEdge",
    name: "Tranchant flamboyant",
    archetypes: [],
    description:
      "Le prochain coup porté est enflammé (+8 dégâts, brûlure). 12 stamina.",
    staminaCost: 12,
    cooldownMs: 4000,
    effectType: "weaponImbue",
    bonusDamage: 8,
    damagePercent: 0.4,
    scalesFrom: "melee",
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.7,
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
  },
  glacialEdge: {
    id: "glacialEdge",
    name: "Tranchant glacial",
    archetypes: [],
    description:
      "Le prochain coup porté est glacé (+6 dégâts, ralentit la cible). 12 stamina.",
    staminaCost: 12,
    cooldownMs: 4000,
    effectType: "weaponImbue",
    bonusDamage: 6,
    damagePercent: 0.4,
    scalesFrom: "melee",
    damageType: "cold",
    inflictsEffect: {
      type: "slow",
      kind: "modifier",
      statModifiers: { moveSpeedPercent: -0.5 },
      durationMs: 2500,
      chance: 0.8,
    },
  },
  shockingEdge: {
    id: "shockingEdge",
    name: "Tranchant foudroyant",
    archetypes: [],
    description:
      "Le prochain coup porté est électrifié (+10 dégâts). 12 stamina.",
    staminaCost: 12,
    cooldownMs: 4000,
    effectType: "weaponImbue",
    bonusDamage: 10,
    damagePercent: 0.4,
    scalesFrom: "melee",
    damageType: "lightning",
  },
  venomEdge: {
    id: "venomEdge",
    name: "Tranchant empoisonné",
    archetypes: [],
    description:
      "Le prochain coup porté est empoisonné (+5 dégâts, poison sur la durée). 12 stamina.",
    staminaCost: 12,
    cooldownMs: 4000,
    effectType: "weaponImbue",
    bonusDamage: 5,
    damagePercent: 0.3,
    scalesFrom: "melee",
    damageType: "poison",
    inflictsEffect: {
      type: "acid",
      kind: "dot",
      chance: 0.8,
      damagePerTick: 4,
      tickIntervalMs: 1000,
      ticks: 3,
    },
  },
  holyEdge: {
    id: "holyEdge",
    name: "Tranchant sacré",
    archetypes: [],
    description: "Le prochain coup porté est béni (+9 dégâts). 12 stamina.",
    staminaCost: 12,
    cooldownMs: 4000,
    effectType: "weaponImbue",
    bonusDamage: 9,
    damagePercent: 0.45,
    scalesFrom: "melee",
    damageType: "holy",
  },
  shadowEdge: {
    id: "shadowEdge",
    name: "Tranchant ténébreux",
    archetypes: [],
    description:
      "Le prochain coup porté est corrompu par l'ombre (+9 dégâts). 12 stamina.",
    staminaCost: 12,
    cooldownMs: 4000,
    effectType: "weaponImbue",
    bonusDamage: 9,
    damagePercent: 0.45,
    scalesFrom: "melee",
    damageType: "shadow",
  },
  fireWall: {
    id: "fireWall",
    name: "Mur de flammes",
    archetypes: ["mage"],
    description:
      "Crée un mur de flammes qui inflige des dégâts sur la durée aux ennemis qui le traversent (20 dégâts). 20 mana.",
    manaCost: 20,
    cooldownMs: 8000,
    effectType: "aoe",
    damage: 20,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "fire",
    radius: 80,
    durationMs: 5000,
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.8, // haute expres - c'est un coup DELIBEREMENT enchante, pas le taux passif habituel d'une arme
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 1,
  },
  flameThrower: {
    id: "flameThrower",
    name: "Jet de flammes",
    archetypes: ["mage"],
    description:
      "Un cône de flammes brûle tout ce qui se trouve devant toi (16 dégâts). 18 mana.",
    manaCost: 18,
    cooldownMs: 4000,
    effectType: "cone",
    damage: 16,
    damagePercent: 0.5,
    scalesFrom: "melee",
    damageType: "fire",
    angleDegrees: 60,
    distance: 90,
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.4,
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 4,
  },
  meteor: {
    id: "meteor",
    name: "Météore",
    archetypes: ["mage"],
    description:
      "Invoque un météore qui s'écrase avec fracas sur la zone visée (35 dégâts). 35 mana.",
    manaCost: 35,
    cooldownMs: 10000,
    effectType: "projectileAoe",
    damage: 35,
    damagePercent: 1,
    scalesFrom: "ranged",
    damageType: "fire",
    radius: 90,
    projectileSpeed: 180, // volontairement lent - le "temps de chute" du meteore
    maxDistance: 450,
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 0.5,
      damagePerTick: 4,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 8,
  },
  fireNova: {
    id: "fireNova",
    name: "Nova de feu",
    archetypes: ["mage"],
    description:
      "Libère une explosion de feu tout autour de toi (22 dégâts). 25 mana.",
    manaCost: 25,
    cooldownMs: 6000,
    effectType: "aoe",
    damage: 22,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "fire",
    radius: 75,
    unlockLevel: 5,
  },

  scoutPulse: {
    id: "scoutPulse",
    name: "Pulsation d'exploration",
    archetypes: [],
    description:
      "Révèle une large zone du brouillard de guerre autour de toi. 1 stamina.",
    staminaCost: 1,
    cooldownMs: 10,
    effectType: "fogPulse",
    radius: 40, // en CASES (coordonnees de tuiles), pas en pixels - different des autres competences
    ignoresWalls: true,
    // disabledBiomes: ["maze1", "maze2"], // ids de biomeConfig.js - absent/vide = utilisable partout
    unlockLevel: null,
  },

  detectTraps: {
    id: "detectTraps",
    name: "Détection de pièges",
    archetypes: [],
    description: "Révèle les pièges cachés à portée de vue. 10 stamina.",
    effectType: "detectTrap",
    cooldownMs: 100,
    staminaCost: 1,
    unlockLevel: null,
    // radius absent -> utilise this.playerVisionRadius par defaut (cf.
    // performDetectTrapAbility) - ajoute radius: N ici si tu veux un
    // rayon fixe different de la vision du heros
  },
  detectSecrets: {
    id: "detectSecrets",
    name: "Détection des secrets",
    archetypes: [],
    description:
      "Révèle plus clairement les leviers et passages cachés à portée de vue. 12 stamina.",
    effectType: "detectSecret",
    cooldownMs: 100,
    staminaCost: 1,
    unlockLevel: null,
  },
  treasureSense: {
    id: "treasureSense",
    name: "Instinct du trésor",
    archetypes: ["voleur"],
    description:
      "Révèle une large zone du brouillard de guerre autour de toi, pratique pour repérer coffres et sorties. 5 stamina.",
    staminaCost: 5,
    cooldownMs: 12000,
    effectType: "fogPulse",
    radius: 25,
    ignoresWalls: false,
    unlockLevel: 3,
  },

  shieldBash: {
    id: "shieldBash",
    name: "Coup de bouclier",
    archetypes: ["guerrier"],
    description:
      "Fonce en ligne droite, percute et repousse les ennemis sur le passage. Nécessite un bouclier équipé. 20 stamina.",
    staminaCost: 20,
    cooldownMs: 6000,
    effectType: "shieldBash",
    requiresShield: true,
    damage: 16,
    damagePercent: 0.6,
    scalesFrom: "melee",
    dashDistance: 150, // en pixels
    dashSpeed: 500,
    knockbackDistance: 40,
    unlockLevel: null,
  },
  taunt: {
    id: "taunt",
    name: "Cri de défi",
    archetypes: ["guerrier"],
    description: "Attire l'attention de tous les ennemis proches. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 10000,
    effectType: "taunt",
    radius: 150, // en pixels, comme les autres AoE
    unlockLevel: null,
  },
  repel: {
    id: "repel",
    name: "Répulsion",
    archetypes: [],
    description: "Repousse tous les ennemis proches. 15 mana.",
    manaCost: 15,
    cooldownMs: 8000,
    effectType: "repel",
    radius: 100,
    knockbackDistance: 80,
    damage: 0, // optionnel - laisse a 0 si tu veux un pur effet de recul, sans degats
    unlockLevel: null,
  },
  stun: {
    id: "stun",
    name: "Étourdissement",
    archetypes: [],
    description:
      "Étourdit tous les ennemis proches, les empêchant d'agir un court moment. 20 mana.",
    manaCost: 20,
    cooldownMs: 10000,
    effectType: "aoeStun",
    radius: 90,
    durationMs: 2500,
    unlockLevel: null,
  },
  summonAlly: {
    id: "summonAlly",
    name: "Invocation",
    archetypes: ["mage"],
    description:
      "Invoque un allié temporaire qui combat à tes côtés, jusqu'à sa mort ou expiration. 30 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "summon",
    summonType: "gazer1", // cle SPRITE_REGISTRY a utiliser pour le visuel - a remplacer par un sprite plus adapte si tu en as un
    durationMs: null, // null = dure jusqu'a la mort uniquement, jamais d'expiration
    hp: 40,
    damage: 8,
    defense: 1,
    damageType: "fire",
    resistances: { fire: 1 },
    unlockLevel: null,
  },
  summonAlly2: {
    id: "summonAlly2",
    name: "Invocation 2",
    archetypes: ["mage"],
    description:
      "Invoque un allié temporaire qui combat à tes côtés, jusqu'à sa mort ou expiration. 30 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "summon",
    summonType: "gazer2", // cle SPRITE_REGISTRY a utiliser pour le visuel - a remplacer par un sprite plus adapte si tu en as un
    durationMs: null, // null = dure jusqu'a la mort uniquement, jamais d'expiration
    hp: 40,
    damage: 8,
    defense: 1,
    damageType: "physical",
    resistances: { physical: 1 },
    unlockLevel: null,
  },
  summonWolf: {
    id: "summonWolf",
    name: "Invocation : Loup",
    archetypes: ["voleur"],
    description: "Invoque un loup rapide mais fragile. 25 stamina.",
    staminaCost: 25,
    cooldownMs: 18000,
    effectType: "summon",
    summonType: "enemyDefault", // remplace par un sprite dedie si tu en as un
    durationMs: 15000,
    hp: 25,
    damage: 12,
    defense: 0,
    damageType: "physical",
  },

  summonIceElemental: {
    id: "summonIceElemental",
    name: "Invocation : Élémentaire de glace",
    archetypes: ["mage"],
    description:
      "Invoque un élémentaire robuste et résistant au froid. 35 mana.",
    manaCost: 35,
    cooldownMs: 25000,
    effectType: "summon",
    summonType: "enemyDefault",
    durationMs: 25000,
    hp: 60,
    damage: 6,
    defense: 3,
    damageType: "cold",
    resistances: { cold: 1, fire: -0.5 },
  },
  summonFamiliar: {
    id: "summonFamiliar",
    name: "Familier",
    archetypes: ["mage"],
    description:
      "Invoque un familier qui te suit d'étage en étage, jusqu'à sa mort. 40 mana.",
    manaCost: 1,
    cooldownMs: 30000,
    effectType: "summon",
    summonType: "wolfFamiliar",
    durationMs: null, // jamais d'expiration par duree - uniquement la mort le fait disparaitre
    hpScale: 0.5,
    damageScale: 0.6,
    defenseScale: 0.5,
    damageType: "physical",
    persistent: true,
  },
  shortDash: {
    id: "shortDash",
    name: "Ruée",
    archetypes: [],
    description: "Téléportation courte dans la direction actuelle. 10 stamina.",
    staminaCost: 10,
    cooldownMs: 4000,
    effectType: "teleportDash",
    distance: 120,
  },
  randomTeleport: {
    id: "randomTeleport",
    name: "Téléportation aléatoire",
    archetypes: [],
    description: "Téléporte vers un point aléatoire de l'étage. 20 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "randomTeleport",
  },
  stealth: {
    id: "stealth",
    name: "Furtivité",
    archetypes: ["voleur"],
    description: "Devient indétectable un court moment. 5 stamina.",
    staminaCost: 5,
    cooldownMs: 8000,
    effectType: "stealth",
    durationMs: 5000,
  },
  lightningBolt: {
    id: "lightningBolt",
    name: "Éclair",
    archetypes: ["mage"],
    description:
      "Un éclair frappe la première cible touchée (18 dégâts). 14 mana.",
    manaCost: 14,
    cooldownMs: 2800,
    effectType: "pierce",
    damage: 18,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "lightning",
    projectileSpeed: 500,
    maxDistance: 420,
    maxPierceCount: 1,
    unlockLevel: 2,
  },
  chainLightningSpell: {
    id: "chainLightningSpell",
    name: "Chaîne d'éclairs",
    archetypes: ["mage"],
    description:
      "L'éclair saute d'ennemi en ennemi (14 dégâts par saut). 22 mana.",
    manaCost: 22,
    cooldownMs: 5000,
    effectType: "chainLightning",
    damage: 14,
    damagePercent: 0.5,
    scalesFrom: "ranged",
    damageType: "lightning",
    maxJumps: 4,
    jumpRange: 130,
    unlockLevel: 5,
  },
  targetedStrike: {
    id: "targetedStrike",
    name: "Frappe ciblée",
    archetypes: ["mage"],
    description:
      "Une décharge concentrée frappe un point précis avec une grande violence (30 dégâts). 28 mana.",
    manaCost: 28,
    cooldownMs: 7000,
    effectType: "projectileAoe",
    damage: 30,
    damagePercent: 0.8,
    scalesFrom: "ranged",
    damageType: "lightning",
    radius: 40,
    projectileSpeed: 450,
    maxDistance: 400,
    unlockLevel: 7,
  },
  staticStorm: {
    id: "staticStorm",
    name: "Tempête statique",
    archetypes: ["mage"],
    description:
      "Une tempête électrique persistante frappe les ennemis alentour (9 dégâts/tick). 32 mana.",
    manaCost: 32,
    cooldownMs: 13000,
    effectType: "zone",
    damagePerTick: 9,
    damagePercent: 0.25,
    scalesFrom: "ranged",
    damageType: "lightning",
    radius: 90,
    tickIntervalMs: 700,
    durationMs: 5000,
    color: 0xffff66,
    unlockLevel: 9,
  },
  thorns: {
    id: "thorns",
    name: "Épines",
    archetypes: ["mage", "archer"],
    description:
      "Des épines jaillissent du sol devant toi (15 dégâts). 12 mana.",
    manaCost: 12,
    cooldownMs: 3500,
    effectType: "cone",
    damage: 15,
    damagePercent: 0.5,
    scalesFrom: "melee",
    damageType: "poison",
    angleDegrees: 70,
    distance: 80,
    unlockLevel: 2,
  },
  ivyWhip: {
    id: "ivyWhip",
    name: "Fouet de lierre",
    archetypes: ["mage"],
    description:
      "Un lierre acéré fouette les ennemis proches (13 dégâts). 15 stamina.",
    staminaCost: 15,
    cooldownMs: 3000,
    effectType: "aoe",
    damage: 13,
    damagePercent: 0.5,
    scalesFrom: "melee",
    damageType: "poison",
    radius: 50,
    unlockLevel: 3,
  },
  spores: {
    id: "spores",
    name: "Spores",
    archetypes: ["mage"],
    description:
      "Libère un nuage de spores qui engourdissent les ennemis proches.",
    manaCost: 18,
    cooldownMs: 6000,
    effectType: "aoeDebuff",
    radius: 60,
    statModifiers: { moveSpeedPercent: -0.35 },
    durationMs: 4000,
    unlockLevel: 5,
  },
  venomousBite: {
    id: "venomousBite",
    name: "Morsure venimeuse",
    archetypes: ["voleur"],
    description:
      "Le prochain coup porté injecte un poison virulent. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 5000,
    effectType: "weaponImbue",
    bonusDamage: 6,
    damagePercent: 0.4,
    scalesFrom: "melee",
    damageType: "poison",
    inflictsEffect: {
      type: "acid",
      kind: "dot",
      chance: 0.85,
      damagePerTick: 4,
      tickIntervalMs: 1000,
      ticks: 4,
    },
    unlockLevel: 4,
  },
  stunningBlow: {
    id: "stunningBlow",
    name: "Coup étourdissant",
    archetypes: ["guerrier"],
    description:
      "Le prochain coup a une chance d'étourdir la cible. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 7000,
    effectType: "weaponImbue",
    bonusDamage: 4,
    damagePercent: 0.2,
    scalesFrom: "melee",
    inflictsEffect: {
      type: "stun",
      kind: "modifier",
      statModifiers: {},
      durationMs: 1200,
      chance: 0.35,
    },
  },
  rendingBlow: {
    id: "rendingBlow",
    name: "Coup déchirant",
    archetypes: ["guerrier", "voleur"],
    description:
      "Le prochain coup a une chance de faire saigner la cible. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 6000,
    effectType: "weaponImbue",
    bonusDamage: 4,
    damagePercent: 0.2,
    scalesFrom: "melee",
    inflictsEffect: {
      type: "bleed",
      kind: "dot",
      chance: 0.5,
      damagePerTick: 4,
      tickIntervalMs: 1000,
      ticks: 4,
    },
  },
  firePool: {
    id: "firePool",
    name: "Mare de feu",
    archetypes: ["mage"],
    description: "Zone de feu persistante. 25 mana.",
    manaCost: 1,
    cooldownMs: 12000,
    effectType: "zone",
    radius: 70,
    durationMs: 6000,
    tickIntervalMs: 800,
    damagePerTick: 5,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "fire",
    color: 0xff6600,
  },
  curse: {
    id: "curse",
    name: "Malédiction",
    archetypes: ["mage"],
    description: "Réduit les dégâts infligés par les ennemis proches. 20 mana.",
    manaCost: 1,
    cooldownMs: 12000,
    effectType: "aoeCurse",
    radius: 100,
    durationMs: 6000,
    damagePercent: -0.4,
  },
  vampiricStrike: {
    id: "vampiricStrike",
    name: "Frappe vampirique",
    archetypes: ["voleur"],
    description:
      "Le prochain coup soigne un % des dégâts infligés. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "weaponImbue",
    healPercent: 0.5,
  },
  riposte: {
    id: "riposte",
    name: "Riposte",
    archetypes: ["guerrier"],
    description:
      "Renvoie une partie des dégâts subis un court moment. 20 stamina.",
    staminaCost: 20,
    cooldownMs: 10000,
    effectType: "riposte",
    durationMs: 4000,
    reflectPercent: 0.5,
  },
  parry: {
    id: "parry",
    name: "Parade",
    archetypes: ["guerrier"],
    description:
      "Réduit fortement les dégâts subis un court instant. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "parry",
    durationMs: 1500,
    damageReduction: 0.8,
  },
  poisonTrap: {
    id: "poisonTrap",
    name: "Piège empoisonné",
    archetypes: ["voleur"],
    description: "Pose un piège qui empoisonne au contact. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "trap",
    damageType: "poison",
    inflictsEffect: {
      type: "poison",
      kind: "dot",
      chance: 1,
      damagePerTick: 3,
      damagePercent: 0.6,
      scalesFrom: "ranged",
      tickIntervalMs: 1000,
      ticks: 4,
    },
    triggerRadius: 20,
    expiresAfterMs: 30000,
  },
  fireTrap: {
    id: "fireTrap",
    name: "Piège incendiaire",
    archetypes: ["voleur"],
    description: "Pose un piège qui enflamme au contact. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "trap",
    damageType: "fire",
    inflictsEffect: {
      type: "burn",
      kind: "dot",
      chance: 1,
      damagePerTick: 4,
      damagePercent: 0.6,
      scalesFrom: "ranged",
      tickIntervalMs: 1000,
      ticks: 3,
    },
    triggerRadius: 20,
    expiresAfterMs: 30000,
  },
  bleedTrap: {
    id: "bleedTrap",
    name: "Piège lacérant",
    archetypes: ["voleur"],
    description: "Pose un piège qui lacère au contact. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "trap",
    inflictsEffect: {
      type: "bleed",
      kind: "dot",
      chance: 1,
      damagePerTick: 3,
      damagePercent: 0.6,
      scalesFrom: "ranged",
      tickIntervalMs: 800,
      ticks: 5,
    },
    triggerRadius: 20,
    expiresAfterMs: 30000,
  },
  freeze: {
    id: "freeze",
    name: "Gel",
    archetypes: ["mage"],
    description: "Projectile qui explose et gèle les ennemis touchés. 18 mana.",
    manaCost: 1,
    cooldownMs: 10, //5000
    effectType: "projectileAoe",
    damage: 10,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "cold",
    radius: 60,
    projectileSpeed: 260,
    maxDistance: 400,
    inflictsEffect: {
      type: "stun",
      kind: "modifier",
      chance: 0.6,
      statModifiers: {},
      durationMs: 1500,
    },
  },
  frozenWall: {
    id: "frozenWall",
    name: "Mur de givre",
    archetypes: ["mage"],
    description:
      "Vague de froid en cône qui ralentit sur son passage. 25 mana.",
    manaCost: 1,
    cooldownMs: 10000,
    effectType: "cone",
    distance: 180,
    angleDegrees: 60,
    damage: 8,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "cold",
    inflictsEffect: {
      type: "slow",
      kind: "modifier",
      chance: 1,
      statModifiers: { moveSpeedPercent: -0.5 },
      durationMs: 3000,
    },
  },
  iceBolt: {
    id: "iceBolt",
    name: "Projectile de glace",
    archetypes: ["mage"],
    description:
      "Un projectile glacé qui ralentit sa cible (12 dégâts). 10 mana.",
    manaCost: 10,
    cooldownMs: 2500,
    effectType: "pierce",
    damage: 12,
    damagePercent: 0.5,
    scalesFrom: "ranged",
    damageType: "cold",
    projectileSpeed: 340,
    maxDistance: 400,
    maxPierceCount: 1,
    inflictsEffect: {
      type: "slow",
      kind: "modifier",
      statModifiers: { moveSpeedPercent: -0.4 },
      durationMs: 2500,
      chance: 0.7,
    },
    unlockLevel: 1,
  },
  freezingRay: {
    id: "freezingRay",
    name: "Rayon gelant",
    archetypes: ["mage"],
    description:
      "Un cône de froid glace tout ce qui se trouve devant toi (14 dégâts). 20 mana.",
    manaCost: 20,
    cooldownMs: 5000,
    effectType: "cone",
    damage: 14,
    damagePercent: 0.5,
    scalesFrom: "melee",
    damageType: "cold",
    angleDegrees: 50,
    distance: 100,
    inflictsEffect: {
      type: "slow",
      kind: "modifier",
      statModifiers: { moveSpeedPercent: -0.6 },
      durationMs: 3000,
      chance: 0.9,
    },
    unlockLevel: 4,
  },
  frostNova: {
    id: "frostNova",
    name: "Nova de givre",
    archetypes: ["mage"],
    description:
      "Une explosion de givre ralentit tous les ennemis proches. 20 mana.",
    manaCost: 20,
    cooldownMs: 6000,
    effectType: "aoeDebuff",
    radius: 70,
    statModifiers: { moveSpeedPercent: -0.5 },
    durationMs: 3000,
    unlockLevel: 3,
  },
  icePrison: {
    id: "icePrison",
    name: "Prison de glace",
    archetypes: ["mage"],
    description: "Enracine tous les ennemis proches dans la glace. 25 mana.",
    manaCost: 25,
    cooldownMs: 9000,
    effectType: "aoeRoot",
    radius: 65,
    durationMs: 2500,
    unlockLevel: 6,
  },
  blizzard: {
    id: "blizzard",
    name: "Blizzard",
    archetypes: ["mage"],
    description:
      "Crée une tempête de glace persistante qui blesse les ennemis qui la traversent (10 dégâts/tick). 30 mana.",
    manaCost: 30,
    cooldownMs: 12000,
    effectType: "zone",
    damagePerTick: 10,
    damagePercent: 0.3,
    scalesFrom: "melee",
    damageType: "cold",
    radius: 80,
    tickIntervalMs: 800,
    durationMs: 6000,
    color: 0x99ddff,
    unlockLevel: 9,
  },
  root: {
    id: "root",
    name: "Racines",
    archetypes: ["mage"],
    description:
      "Bloque le mouvement des ennemis proches (ils peuvent encore attaquer). 18 mana.",
    manaCost: 1,
    cooldownMs: 9000,
    effectType: "aoeRoot",
    radius: 90,
    durationMs: 3000,
  },
  stoneThrow: {
    id: "stoneThrow",
    name: "Projection de pierre",
    archetypes: ["mage", "archer"],
    description: "Projette un bloc de pierre sur ta cible (16 dégâts). 8 mana.",
    manaCost: 8,
    cooldownMs: 2200,
    effectType: "pierce",
    damage: 16,
    damagePercent: 0.5,
    scalesFrom: "ranged",
    damageType: "physical",
    projectileSpeed: 300,
    maxDistance: 380,
    maxPierceCount: 1,
    unlockLevel: 1,
  },
  localizedQuake: {
    id: "localizedQuake",
    name: "Séisme localisé",
    archetypes: ["mage", "guerrier"],
    description:
      "Fait trembler le sol, étourdissant les ennemis proches (18 dégâts). 24 mana.",
    manaCost: 24,
    cooldownMs: 8000,
    effectType: "aoeStun",
    damage: 18,
    radius: 65,
    durationMs: 1500,
    unlockLevel: 6,
  },
  earthLance: {
    id: "earthLance",
    name: "Lance de terre",
    archetypes: ["mage"],
    description:
      "Une lance de pierre transperce les ennemis alignés (20 dégâts). 18 mana.",
    manaCost: 18,
    cooldownMs: 4500,
    effectType: "pierce",
    damage: 20,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    damageType: "physical",
    projectileSpeed: 320,
    maxDistance: 400,
    maxPierceCount: 3,
    unlockLevel: 5,
  },
  magicMissile: {
    id: "magicMissile",
    name: "Projectile magique",
    archetypes: ["mage"],
    description:
      "Un projectile d'énergie arcanique basique, fiable et peu coûteux (10 dégâts). 6 mana.",
    manaCost: 6,
    cooldownMs: 1800,
    effectType: "pierce",
    damage: 10,
    damagePercent: 0.45,
    scalesFrom: "ranged",
    damageType: "arcane",
    projectileSpeed: 360,
    maxDistance: 380,
    maxPierceCount: 1,
    unlockLevel: 1,
  },
  energyRay: {
    id: "energyRay",
    name: "Rayon d'énergie",
    archetypes: ["mage"],
    description:
      "Un rayon d'énergie pure explose au contact (20 dégâts). 20 mana.",
    manaCost: 20,
    cooldownMs: 4500,
    effectType: "projectileAoe",
    damage: 20,
    damagePercent: 0.65,
    scalesFrom: "ranged",
    damageType: "arcane",
    radius: 55,
    projectileSpeed: 340,
    maxDistance: 400,
    unlockLevel: 4,
  },
  arcaneExplosion: {
    id: "arcaneExplosion",
    name: "Explosion arcanique",
    archetypes: ["mage"],
    description:
      "Libère une violente explosion d'énergie arcanique autour de toi (26 dégâts). 30 mana.",
    manaCost: 30,
    cooldownMs: 7000,
    effectType: "aoe",
    damage: 26,
    damagePercent: 0.7,
    scalesFrom: "melee",
    damageType: "arcane",
    radius: 70,
    unlockLevel: 7,
  },
  boomerangAxe: {
    id: "boomerangAxe",
    name: "Hache boomerang",
    archetypes: ["guerrier"],
    description: "Lance une hache qui revient après son trajet. 18 stamina.",
    staminaCost: 18,
    cooldownMs: 6000,
    effectType: "boomerang",
    damage: 12,
    damagePercent: 0.6,
    scalesFrom: "ranged",
    projectileSpeed: 300,
    maxDistance: 250,
  },
  vortex: {
    id: "vortex",
    name: "Vortex",
    archetypes: ["mage"],
    description: "Attire tous les ennemis proches vers toi. 20 mana.",
    manaCost: 1,
    cooldownMs: 10000,
    effectType: "vortex",
    radius: 150,
    pullDistance: 80,
  },
  execute: {
    id: "execute",
    name: "Exécution",
    archetypes: [],
    description:
      "Le prochain coup inflige des dégâts massifs si la cible est sous 25% de PV. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 8000,
    effectType: "weaponImbue",
    executeThreshold: 0.25,
    executeBonusMultiplier: 3,
  },
  extendedVision: {
    id: "extendedVision",
    name: "Vision perçante",
    archetypes: [],
    description: "Augmente ta portée de vue un moment. 15 mana.",
    manaCost: 1,
    cooldownMs: 15000,
    effectType: "visionBuff",
    visionBonus: 4,
    durationMs: 10000,
  },
  bloodPact: {
    id: "bloodPact",
    name: "Pacte de sang",
    archetypes: ["mage"],
    description: "Convertit des PV en mana instantanément.",
    cooldownMs: 15000,
    effectType: "bloodPact",
    hpCost: 20,
    resourceGain: 30,
    resourceType: "mana",
  },
  berserker: {
    id: "berserker",
    name: "Rage berserker",
    archetypes: ["guerrier"],
    description:
      "Sous 30% de PV : +80% dégâts, -30% défense un moment. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 15000,
    effectType: "conditionalBuff",
    hpThresholdPercent: 0.3,
    durationMs: 6000,
    buffStatModifiers: {
      meleeDamagePercent: 0.8,
      rangedDamagePercent: 0.8,
      defensePercent: -0.3,
    },
  },
  recklessRage: {
    id: "recklessRage",
    name: "Rage à double tranchant",
    archetypes: ["guerrier"],
    description: "+50% dégâts, -25% défense, sans condition. 15 stamina.",
    staminaCost: 15,
    cooldownMs: 10000,
    effectType: "selfBuff",
    durationMs: 6000,
    buffStatModifiers: {
      meleeDamagePercent: 0.5,
      rangedDamagePercent: 0.5,
      defensePercent: -0.25,
    },
  },
  shadowRay: {
    id: "shadowRay",
    name: "Rayon des ténèbres",
    archetypes: ["mage"],
    description:
      "Un rayon d'ombre corrosif transperce ta cible (17 dégâts). 16 mana.",
    manaCost: 16,
    cooldownMs: 3500,
    effectType: "pierce",
    damage: 17,
    damagePercent: 0.55,
    scalesFrom: "ranged",
    damageType: "shadow",
    projectileSpeed: 320,
    maxDistance: 400,
    maxPierceCount: 1,
    unlockLevel: 3,
  },
  curseOfWeakness: {
    id: "curseOfWeakness",
    name: "Malédiction d'affaiblissement",
    archetypes: ["mage"],
    description:
      "Maudit les ennemis proches, augmentant fortement les dégâts qu'ils subissent. 22 mana.",
    manaCost: 22,
    cooldownMs: 9000,
    effectType: "aoeCurse",
    radius: 70,
    damagePercent: 0.4,
    durationMs: 5000,
    unlockLevel: 5,
  },
  summonSkeleton: {
    id: "summonSkeleton",
    name: "Invocation de squelette",
    archetypes: ["mage"],
    description:
      "Invoque un squelette guerrier pour combattre à tes côtés. 30 mana.",
    manaCost: 30,
    cooldownMs: 15000,
    effectType: "summon",
    summonType: "skeletonWarrior", // doit exister dans spriteRegistry.js
    damageType: "physical",
    hpScale: 0.5,
    damageScale: 0.4,
    defenseScale: 0.3,
    durationMs: 30000,
    persistent: false,
    unlockLevel: 6,
  },
  holyRay: {
    id: "holyRay",
    name: "Rayon sacré",
    archetypes: ["mage", "guerrier"],
    description:
      "Un rayon de lumière sacrée transperce ta cible (16 dégâts). 15 mana.",
    manaCost: 15,
    cooldownMs: 3200,
    effectType: "pierce",
    damage: 16,
    damagePercent: 0.5,
    scalesFrom: "ranged",
    damageType: "holy",
    projectileSpeed: 340,
    maxDistance: 400,
    maxPierceCount: 1,
    unlockLevel: 3,
  },
  smite: {
    id: "smite",
    name: "Châtiment",
    archetypes: ["mage", "guerrier"],
    description: "Frappe la zone d'une lumière punitive (24 dégâts). 26 mana.",
    manaCost: 26,
    cooldownMs: 7000,
    effectType: "aoe",
    damage: 24,
    damagePercent: 0.65,
    scalesFrom: "melee",
    damageType: "holy",
    radius: 65,
    unlockLevel: 6,
  },
  spectralBlade: {
    id: "spectralBlade",
    name: "Lame spectrale",
    archetypes: ["guerrier"],
    description:
      "Une lame d'énergie transperce les ennemis alignés (19 dégâts). 18 stamina.",
    staminaCost: 18,
    cooldownMs: 4000,
    effectType: "pierce",
    damage: 19,
    damagePercent: 0.6,
    scalesFrom: "melee",
    damageType: "physical",
    projectileSpeed: 380,
    maxDistance: 350,
    maxPierceCount: 2,
    unlockLevel: 4,
  },
  forceProjectile: {
    id: "forceProjectile",
    name: "Projectile de force",
    archetypes: ["guerrier", "archer"],
    description:
      "Concentre ta force en un projectile brutal (18 dégâts). 16 stamina.",
    staminaCost: 16,
    cooldownMs: 3500,
    effectType: "pierce",
    damage: 18,
    damagePercent: 0.55,
    scalesFrom: "melee",
    damageType: "physical",
    projectileSpeed: 350,
    maxDistance: 350,
    maxPierceCount: 1,
    unlockLevel: 3,
  },
  shockwave: {
    id: "shockwave",
    name: "Onde de choc",
    archetypes: ["guerrier"],
    description:
      "Une onde de choc repousse et blesse tous les ennemis proches (15 dégâts). 22 stamina.",
    staminaCost: 22,
    cooldownMs: 6000,
    effectType: "repel",
    damage: 15,
    damagePercent: 0.5,
    scalesFrom: "melee",
    damageType: "physical",
    radius: 60,
    knockbackDistance: 60,
    unlockLevel: 5,
  },
  bruteForce: {
    id: "bruteForce",
    name: "Force brute",
    archetypes: [],
    description:
      "Augmente fortement tes dégâts au corps à corps pendant un court moment. 20 stamina.",
    staminaCost: 20,
    cooldownMs: 10000,
    effectType: "selfBuff",
    statModifiers: { meleeDamagePercent: 0.5 },
    durationMs: 5000,
    unlockLevel: 4,
  },
  precision: {
    id: "precision",
    name: "Précision",
    archetypes: [],
    description:
      "Augmente fortement tes dégâts à distance pendant un court moment. 20 stamina.",
    staminaCost: 20,
    cooldownMs: 10000,
    effectType: "selfBuff",
    statModifiers: { rangedDamagePercent: 0.5 },
    durationMs: 5000,
    unlockLevel: 4,
  },
  preciseStrike: {
    id: "preciseStrike",
    name: "Frappe précise",
    archetypes: [],
    description:
      "Augmente fortement tes chances de coup critique sur le prochain coup. 12 stamina.",
    staminaCost: 12,
    cooldownMs: 6000,
    effectType: "weaponImbue",
    critChanceBonus: 0.35, // s'ajoute a CRIT_CHANCE, pour CE coup uniquement
  },
  manaShield: {
    id: "manaShield",
    name: "Armure de mana",
    archetypes: ["mage"],
    description:
      "Renforce ta défense en puisant dans ton énergie magique pendant un court moment. 15 mana.",
    manaCost: 15,
    cooldownMs: 8000,
    effectType: "selfBuff",
    statModifiers: { defensePercent: 0.6 },
    durationMs: 6000,
    unlockLevel: 4,
  },
};

/**
 * Resout la definition d'une competence par son id - repli generique si
 * elle n'est pas (encore) connue du client, meme principe que
 * resolveItemDef.
 */
export function resolveAbilityDef(abilityId) {
  return (
    ABILITY_DEFS[abilityId] || {
      id: abilityId,
      name: abilityId,
      archetypes: [],
      staminaCost: 10,
      cooldownMs: 2000,
      effectType: "aoe",
      damage: 5,
      radius: 50,
      unlockLevel: null,
    }
  );
}
