/**
 * Miroir CLIENT des définitions d'objets - cf. server/services/generation/itemTypes.js,
 * la vraie source de vérité pour ce qui TOMBE (quel objet, où, à quelle
 * fréquence). `statBonus`/`effect`/`price` sont recopiés ici aussi
 * désormais (utilisés par equipment.js pour les bonus de stats, par
 * l'utilisation des consommables, et par la vente en boutique - cf.
 * MainScene.sellItem) - le serveur reste seul décideur de ce qui tombe,
 * mais une fois l'objet en inventaire, appliquer son effet ou calculer
 * son prix de revente est une opération purement locale, pas besoin
 * d'aller-retour serveur.
 *
 * Les deux fichiers doivent rester synchronisés à la main (mêmes clés,
 * mêmes statBonus/effect) - exactement la même discipline que
 * spriteRegistry.js (clés client) vs enemyStats.js/biomeConfig.js (clés
 * serveur) déjà en place ailleurs dans le projet.
 *
 * Les objets présents ici si ils ne sont pas présents dans le serveur ne pourront
 * jamais être looter ou achetés mais peuvent exister dans l'inventaire local
 * et etre vendu localement dans une boutique et racheter dans cette même boutique.
 */
export const ITEM_DEFS = {
  woodenDagger: {
    id: "woodenDagger",
    category: "equipment",
    slot: "mainHand", // une main - peut cohabiter avec un bouclier (offHand) ou une seconde arme (double armement automatique si offHand est libre, cf. MainScene.equipItem)
    twoHanded: false,
    grantsRanged: false, // explicite plutot qu'absent - purement melee, ne debloque jamais l'attaque a distance seule (cf. MainScene.canUseRangedAttack)
    name: "Dague en bois",
    description:
      "+1 dégât au corps à corps et -2 à la distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: -2 },
    stackable: false,
    archetypes: ["voleur"],
    price: 2,
  },
  woodenSword: {
    id: "woodenSword",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Épée en bois",
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    archetypes: ["guerrier"],
    damageType: "cold",
    price: 2,
    inflictsEffect: {
      type: "bleed",
      chance: 0.9,
      damagePerTick: 1,
      tickIntervalMs: 1000,
      ticks: 3,
    },
  },

  woodenBow: {
    id: "woodenBow",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true, // occupe les DEUX mains - equiper libere mainHand ET offHand (cf. MainScene.equipItem)
    grantsRanged: true, // sans arme marquee ainsi equipee (ici ou en offHand), l'attaque a distance est indisponible - cf. MainScene.canUseRangedAttack
    requiresAmmo: ["woodenArrow", "bronzeArrow", "bigWoodenArrow"], // itemId EXACT requis (pas juste un booleen) - un carreau ne peut pas alimenter un arc, cf. MainScene.performRangedAttack
    name: "Arc en bois",
    description:
      "+1 dégât à distance. Nécessite des flèches. Arme d'entraînement de départ.",
    statBonus: { rangedDamage: 1 },
    stackable: false,
    archetypes: ["archer"],
    price: 2,
  },
  woodenCrossbow: {
    id: "woodenCrossbow",
    category: "equipment",
    slot: "offHand",
    twoHanded: false,
    grantsRanged: true,
    requiresAmmo: ["woodenCrossbowBolt"],
    name: "Arbalète en bois",
    description:
      "+1 dégât à distance, Nécessite des carreaux. +1 de distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { rangedDamage: 1, rangedRange: 1 },
    archetypes: ["archer", "voleur"],
    stackable: false,
    price: 2,
  },
  woodenSpear: {
    id: "woodenSpear",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Lance en bois",
    description:
      "+1 dégât au corps à corps. +2 de distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: 2 },
    stackable: false,
    archetypes: ["guerrier", "voleur"],
    price: 2,
  },
  woodenAxe: {
    id: "woodenAxe",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Hache de guerre en bois",
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    archetypes: ["guerrier"],
    price: 2,
  },
  woodenMallet: {
    id: "woodenMallet",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Masse en bois",
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    archetypes: ["guerrier"],
    price: 2,
  },
  woodenShovel: {
    id: "woodenShovel",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Pelle en bois",
    description:
      "+1 dégât au corps à corps. +1 de distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: 1 },
    stackable: false,
    archetypes: ["guerrier", "voleur"],
    price: 2,
  },
  woodenPickaxe: {
    id: "woodenPickaxe",
    category: "equipment",
    slot: "tool",
    name: "Pioche en bois",
    description: "Outil de minage basique. Niveau 1.",
    toolTier: 1,
    stackable: false,
    price: 20,
  },
  woodenHammer: {
    id: "woodenHammer",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Marteau de guerre en bois",
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    archetypes: ["guerrier", "voleur"],
    price: 2,
  },
  woodenSickle: {
    id: "woodenSickle",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Faucille en bois",
    description:
      "+1 dégât au corps à corps. +1 de distance d'attaque  Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: 1 },
    stackable: false,
    archetypes: ["guerrier", "voleur"],
    price: 2,
  },

  woodenShield: {
    id: "woodenShield",
    category: "equipment",
    slot: "offHand",
    isShield: true,
    twoHanded: false,
    grantsRanged: false,
    name: "Bouclier en bois",
    description: "+1 défense. Équipement d'entraînement de départ.",
    statBonus: { defense: 1 },
    archetypes: ["guerrier"],
    stackable: false,
    price: 2,
  },

  woodenStaff: {
    id: "woodenStaff",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: true,
    requiresAmmo: false,
    manaCost: 1,
    name: "Bâton en bois",
    description:
      "+1 dégât à distance. Canalise la magie (1 mana par tir), sans munitions. Arme d'entraînement de départ.",
    statBonus: { rangedDamage: 1 },
    stackable: false,
    archetypes: ["mage"],
    // inflictsEffect: {
    //   type: "slow",
    //   kind: "modifier", // <-- le champ qui manquait, decide TOUT le comportement
    //   chance: 1,
    //   statModifiers: { moveSpeedPercent: -0.4 }, // -40% de vitesse
    //   durationMs: 2500, // duree en ms, PAS ticks/tickIntervalMs/damagePerTick (ca c'est la forme DOT)
    // },
    price: 2,
  },
  ironDagger: {
    id: "ironDagger",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Dague en fer",
    description: "+4 dégâts au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    archetypes: ["voleur", "guerrier", "archer", "mage"],
    unlockLevel: 2,
    price: 40,
  },
  sharpIronDagger: {
    id: "sharpIronDagger",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Dague en fer aiguisée. Inflige un saignement à l'ennemi.",
    description: "+5 dégâts au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    archetypes: ["voleur", "guerrier", "archer", "mage"],
    inflictsEffect: {
      type: "bleed",
      kind: "dot", // damage over time
      chance: 1,
      damagePerTick: 1,
      tickIntervalMs: 1000,
      durationMs: 5000,
    },
    unlockLevel: 3,
    price: 60,
  },
  ironSword: {
    id: "ironSword",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Épée de fer",
    description: "+5 dégâts au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 60,
  },
  sharpIronSword: {
    id: "sharpIronSword",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Épée en fer aiguisée",
    description:
      "+6 dégâts au corps à corps. Inflige un saignement à l'ennemi.",
    statBonus: { meleeDamage: 6 },
    stackable: false,
    archetypes: ["guerrier"],
    inflictsEffect: {
      type: "bleed",
      kind: "dot", // damage over time
      chance: 1,
      damagePerTick: 1,
      tickIntervalMs: 1000,
      durationMs: 5000,
    },
    unlockLevel: 3,
    price: 80,
  },

  huntingBow: {
    id: "huntingBow",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: true,
    requiresAmmo: ["woodenArrow", "ironArrow", "bronzeArrow", "bigWoodenArrow"],
    name: "Arc de chasse",
    description: "+4 dégâts à distance. +5 de distance d'attaque",
    unique: true,
    statBonus: { rangedDamage: 4, rangedRange: 5 },
    stackable: false,
    archetypes: ["archer"],
    unlockLevel: 2,
    price: 55,
  },
  crossbow: {
    id: "crossbow",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: true,
    requiresAmmo: ["woodenCrossbowBolt", "ironCrossbowBolt"],
    name: "Arbalète",
    description: "+3 dégâts à distance. Se manie a une main.",
    statBonus: { rangedDamage: 3, rangedRange: 5 },
    stackable: false,
    archetypes: ["archer", "voleur"],
    unlockLevel: 2,
    price: 50,
  },
  ironSpear: {
    id: "ironSpear",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Lance en fer",
    description: "+4 dégât au corps à corps. +3 de distance d'attaque.",
    statBonus: { meleeDamage: 4, meleeRange: 3 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 55,
  },
  ironAxe: {
    id: "ironAxe",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Hache de guerre en fer",
    description: "+6 dégât au corps à corps.",
    statBonus: { meleeDamage: 6 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 65,
  },
  ironMallet: {
    id: "ironMallet",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Masse en fer",
    description: "+5 dégât au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 60,
  },
  ironShovel: {
    id: "ironShovel",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Pelle en fer",
    description: "+4 dégât au corps à corps. +1 de distance d'attaque.",
    statBonus: { meleeDamage: 4, meleeRange: +1 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 55,
  },
  ironPickaxe: {
    id: "ironPickaxe",
    category: "equipment",
    slot: "tool",
    name: "Pioche en fer",
    description: "Outil de minage robuste. Niveau 2.",
    toolTier: 2,
    stackable: false,
    price: 60,
  },
  ironHammer: {
    id: "ironHammer",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Marteau de guerre en fer",
    description: "+4 dégât au corps à corps.",
    statBonus: { meleeDamage: 4 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 50,
  },
  ironSickle: {
    id: "ironSickle",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Faucille en fer",
    description: "+5 dégât au corps à corps. +2 de distance d'attaque.",
    statBonus: { meleeDamage: 5, meleeRange: 2 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 2,
    price: 60,
  },
  bronzeDagger: {
    id: "bronzeDagger",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Dague en bronze",
    description: "+10 dégâts au corps à corps.",
    statBonus: { meleeDamage: 10 },
    stackable: false,
    archetypes: ["voleur", "guerrier", "archer", "mage"],
    unlockLevel: 5,
    price: 100,
  },
  bronzeSword: {
    id: "bronzeSword",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Épée de bronze",
    description: "+12 dégâts au corps à corps. +2 de distance d'attaque.",
    statBonus: { meleeDamage: 12, meleeRange: +2 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 135,
  },
  warBow: {
    id: "warBow",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: true,
    requiresAmmo: ["woodenArrow", "ironArrow", "acidArrow"],
    name: "Arc de guerre",
    description: "+10 dégâts à distance. +8 de distance d'attaque.",
    statBonus: { rangedDamage: 10, rangedRange: 8 },
    stackable: false,
    archetypes: ["archer"],
    unlockLevel: 5,
    price: 140,
  },
  warCrossbow: {
    id: "warCrossbow",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: true,
    requiresAmmo: [
      "woodenCrossbowBolt",
      "ironCrossbowBolt",
      "acidCrossbowBolt",
    ],
    name: "Arbalète",
    description: "+3 dégâts à distance. Se manie a une main.",
    statBonus: { rangedDamage: 6, rangedRange: 6 },
    stackable: false,
    archetypes: ["archer", "voleur"],
    unlockLevel: 5,
    price: 110,
  },
  bronzeSpear: {
    id: "bronzeSpear",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Lance en bronze",
    description: "+8 dégât au corps à corps. +4 de distance d'attaque.",
    statBonus: { meleeDamage: 8, meleeRange: 4 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 125,
  },
  bronzeAxe: {
    id: "bronzeAxe",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Hache de guerre en bronze",
    description: "+12 dégât au corps à corps.",
    statBonus: { meleeDamage: 12 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 130,
  },
  bronzeMallet: {
    id: "bronzeMallet",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Masse en bronze",
    description: "+10 dégât au corps à corps.",
    statBonus: { meleeDamage: 10 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 125,
  },
  bronzeShovel: {
    id: "bronzeShovel",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Pelle en bronze",
    description: "+8 dégât au corps à corps. +2 de distance d'attaque.",
    statBonus: { meleeDamage: 8, meleeRange: +2 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 120,
  },
  bronzePickaxe: {
    id: "bronzePickaxe",
    category: "equipment",
    slot: "tool",
    name: "Pioche en bronze",
    description: "Outil de minage précis. Niveau 3.",
    toolTier: 3,
    stackable: false,
    price: 150,
  },
  bronzeHammer: {
    id: "bronzeHammer",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Marteau de guerre en bronze",
    description: "+8 dégât au corps à corps.",
    statBonus: { meleeDamage: 8 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 110,
  },
  bronzeSickle: {
    id: "bronzeSickle",
    category: "equipment",
    slot: "mainHand",
    twoHanded: true,
    grantsRanged: false,
    name: "Faucille en bronze",
    description: "+10 dégât au corps à corps. +3 de distance d'attaque.",
    statBonus: { meleeDamage: 10, meleeRange: 3 },
    stackable: false,
    archetypes: ["guerrier"],
    unlockLevel: 5,
    price: 135,
  },
  woodenArrow: {
    id: "woodenArrow",
    category: "ammo",
    slot: "quiver",
    name: "Flèche en bois",
    description: "+1 dégât à distance tant que des flèches sont encochées.",
    statBonus: { rangedDamage: 1 },
    stackable: true,
    archetypes: ["archer"],
    unlockLevel: 1,
    price: 1,
    inflictsEffect: {
      type: "slow",
      kind: "modifier", // <-- le champ qui manquait, decide TOUT le comportement
      chance: 1,
      statModifiers: { moveSpeedPercent: -0.4 }, // -40% de vitesse
      durationMs: 2500, // duree en ms, PAS ticks/tickIntervalMs/damagePerTick (ca c'est la forme DOT)
    },
  },
  bigWoodenArrow: {
    id: "bigWoodenArrow",
    category: "ammo",
    slot: "quiver",
    name: "Flèche en bois géante",
    description: "+5 dégât à distance tant que des flèches sont encochées.",
    statBonus: { rangedDamage: 5 },
    stackable: true,
    archetypes: ["archer"],
    unlockLevel: 1,
    price: 15,
    // inflictsEffect: {
    //   type: "slow",
    //   kind: "modifier", // <-- le champ qui manquait, decide TOUT le comportement
    //   chance: 1,
    //   statModifiers: { moveSpeedPercent: -0.4 }, // -40% de vitesse
    //   durationMs: 2500, // duree en ms, PAS ticks/tickIntervalMs/damagePerTick (ca c'est la forme DOT)
    // },
  },
  woodenCrossbowBolt: {
    id: "woodenCrossbowBolt",
    category: "ammo",
    slot: "quiver",
    name: "Carreau en bois",
    description:
      "+1 dégât à distance tant que des carreaux sont disponibles. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 1 },
    stackable: true,
    archetypes: ["archer", "voleur"],
    unlockLevel: 1,
    price: 1,
  },
  ironArrow: {
    id: "ironArrow",
    category: "ammo",
    slot: "quiver",
    name: "Flèche en fer",
    description: "+7 dégât à distance tant que des flèches sont encochées.",
    statBonus: { rangedDamage: 7 },
    stackable: true,
    archetypes: ["archer"],
    unlockLevel: 3,
    price: 12,
  },
  ironCrossbowBolt: {
    id: "ironCrossbowBolt",
    category: "ammo",
    slot: "quiver",
    name: "Carreau de fer",
    description:
      "+5 dégât à distance tant que des carreaux sont encochés. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 5 },
    stackable: true,
    archetypes: ["archer", "voleur"],
    unlockLevel: 3,
    price: 10,
  },
  bronzeArrow: {
    id: "bronzeArrow",
    category: "ammo",
    slot: "quiver",
    name: "Flèche en bronze",
    description: "+15 dégât à distance tant que des flèches sont encochées.",
    statBonus: { rangedDamage: 15 },
    stackable: true,
    archetypes: ["archer"],
    unlockLevel: 5,
    price: 35,
  },
  bronzeCrossbowBolt: {
    id: "bronzeCrossbowBolt",
    category: "ammo",
    slot: "quiver",
    name: "Carreau de bronze",
    description:
      "+12 dégât à distance et +2 de distance d'attaque tant que des carreaux sont encochés. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 12, rangedRange: 2 },
    stackable: true,
    archetypes: ["archer", "voleur"],
    unlockLevel: 5,
    price: 33,
  },
  acidArrow: {
    id: "acidArrow",
    category: "ammo",
    slot: "quiver",
    name: "Flèche d'acide",
    description: "+15 dégât à distance tant que des flèches sont encochées.",
    statBonus: { rangedDamage: 15 },
    stackable: true,
    archetypes: ["archer"],
    inflictsEffect: {
      // chance d'infliger un effet par coup - PAS de cooldown ici
      type: "acid",
      kind: "dot",
      chance: 0.3,
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    unlockLevel: 5,
    price: 45,
  },
  acidCrossbowBolt: {
    id: "acidCrossbowBolt",
    category: "ammo",
    slot: "quiver",
    name: "Carreau d'acide",
    description:
      "+12 dégât à distance et +2 de distance d'attaque tant que des carreaux sont encochés. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 12, rangedRange: 2 },
    stackable: true,
    archetypes: ["archer", "voleur"],
    unlockLevel: 5,
    price: 43,
  },

  /** Potions **/

  healthPotion: {
    id: "healthPotion",
    category: "consumable",
    name: "Petite potion de soin",
    description: "Restaure 30 PV à l'usage.",
    effect: { heal: 30 },
    stackable: true,
    unlockLevel: 1,
    price: 15, // vendable en boutique - cf. shopGenerator.js. Absent = jamais en vente (or, objets de quete)
  },
  mediumHealthPotion: {
    id: "mediumHealthPotion",
    category: "consumable",
    name: "Moyenne potion de soin",
    description: "Restaure 60 PV à l'usage.",
    effect: { heal: 60 },
    stackable: true,
    unlockLevel: 3,
    price: 50,
  },
  largeHealthPotion: {
    id: "largeHealthPotion",
    category: "consumable",
    name: "Grande potion de soin",
    description: "Restaure 120 PV à l'usage.",
    effect: { heal: 120 },
    stackable: true,
    unlockLevel: 5,
    price: 200,
  },
  manaPotion: {
    id: "manaPotion",
    category: "consumable",
    name: "Petite potion de mana",
    description: "Restaure 20 PM à l'usage.",
    effect: { mana: 20 },
    stackable: true,
    archetypes: ["mage"],
    unlockLevel: 1,
    price: 12,
  },
  mediumManaPotion: {
    id: "mediumManaPotion",
    category: "consumable",
    name: "Moyenne potion de mana",
    description: "Restaure 40 PM à l'usage.",
    effect: { mana: 40 },
    stackable: true,
    archetypes: ["mage"],
    unlockLevel: 3,
    price: 45,
  },
  largeManaPotion: {
    id: "largeManaPotion",
    category: "consumable",
    name: "Grande potion de mana",
    description: "Restaure 80 PM à l'usage.",
    effect: { mana: 80 },
    stackable: true,
    archetypes: ["mage"],
    unlockLevel: 5,
    price: 150,
  },
  staminaPotion: {
    id: "staminaPotion",
    category: "consumable",
    name: "Potion de stamina",
    description: "Restaure 40 points de stamina à l'usage.",
    effect: { stamina: 40 },
    stackable: true,
    unlockLevel: 1,
    price: 20,
  },
  mediumStaminaPotion: {
    id: "mediumStaminaPotion",
    category: "consumable",
    name: "Moyenne potion de stamina",
    description: "Restaure 80 points de stamina à l'usage.",
    effect: { stamina: 80 },
    stackable: true,
    unlockLevel: 3,
    price: 50,
  },
  largeStaminaPotion: {
    id: "largeStaminaPotion",
    category: "consumable",
    name: "Grande potion de stamina",
    description: "Restaure 120 points de stamina à l'usage.",
    effect: { stamina: 120 },
    stackable: true,
    unlockLevel: 5,
    price: 120,
  },
  hybridPotion: {
    id: "hybridPotion",
    category: "consumable",
    name: "Élixir hybride",
    description: "Restaure 25 PV, 25 mana et 25 stamina à l'usage.",
    effect: { heal: 25, mana: 25, stamina: 25 },
    stackable: true,
    unlockLevel: 6,
    price: 70,
  },
  mediumHybridPotion: {
    id: "mediumHybridPotion",
    category: "consumable",
    name: "Moyen élixir hybride",
    description: "Restaure 50 PV, 50 mana et 50 stamina à l'usage.",
    effect: { heal: 50, mana: 50, stamina: 50 },
    stackable: true,
    unlockLevel: 4,
    price: 100,
  },
  largeHybridPotion: {
    id: "largeHybridPotion",
    category: "consumable",
    name: "Grand élixir hybride",
    description: "Restaure 100 PV, 100 mana et 100 stamina à l'usage.",
    effect: { heal: 100, mana: 100, stamina: 100 },
    stackable: true,
    unlockLevel: 6,
    price: 200,
  },

  strengthPotion: {
    id: "strengthPotion",
    category: "consumable",
    name: "Potion de force",
    description:
      "Augmente tes dégâts au corps à corps pendant un court moment.",
    effect: {
      buff: { statModifiers: { meleeDamagePercent: 0.4 }, durationMs: 30000 },
    },
    stackable: true,
    unlockLevel: 3,
    price: 35,
  },
  mediumStrengthPotion: {
    id: "mediumStrengthPotion",
    category: "consumable",
    name: "Moyenne potion de force",
    description:
      "Augmente tes dégâts au corps à corps pendant un court moment.",
    effect: {
      buff: { statModifiers: { meleeDamagePercent: 0.6 }, durationMs: 40000 },
    },
    stackable: true,
    unlockLevel: 4,
    price: 50,
  },
  largeStrengthPotion: {
    id: "largeStrengthPotion",
    category: "consumable",
    name: "Grande potion de force",
    description:
      "Augmente tes dégâts au corps à corps pendant un court moment.",
    effect: {
      buff: { statModifiers: { meleeDamagePercent: 0.8 }, durationMs: 50000 },
    },
    stackable: true,
    unlockLevel: 5,
    price: 70,
  },
  swiftnessPotion: {
    id: "swiftnessPotion",
    category: "consumable",
    name: "Potion de vitesse",
    description: "Augmente ta vitesse de déplacement pendant un court moment.",
    effect: {
      buff: { statModifiers: { moveSpeedPercent: 0.5 }, durationMs: 20000 },
    },
    stackable: true,
    unlockLevel: 3,
    price: 30,
  },
  mediumSwiftnessPotion: {
    id: "mediumSwiftnessPotion",
    category: "consumable",
    name: "Moyenne potion de vitesse",
    description: "Augmente ta vitesse de déplacement pendant un court moment.",
    effect: {
      buff: { statModifiers: { moveSpeedPercent: 0.7 }, durationMs: 30000 },
    },
    stackable: true,
    unlockLevel: 4,
    price: 45,
  },
  largeSwiftnessPotion: {
    id: "largeSwiftnessPotion",
    category: "consumable",
    name: "Grande potion de vitesse",
    description: "Augmente ta vitesse de déplacement pendant un court moment.",
    effect: {
      buff: { statModifiers: { moveSpeedPercent: 0.9 }, durationMs: 40000 },
    },
    stackable: true,
    unlockLevel: 5,
    price: 60,
  },
  fortifyPotion: {
    id: "fortifyPotion",
    category: "consumable",
    name: "Potion de fortification",
    description: "Augmente fortement ta défense pendant un court moment.",
    effect: {
      buff: { statModifiers: { defensePercent: 0.5 }, durationMs: 25000 },
    },
    stackable: true,
    unlockLevel: 4,
    price: 40,
  },
  mediumFortifyPotion: {
    id: "mediumFortifyPotion",
    category: "consumable",
    name: "Moyenne potion de fortification",
    description: "Augmente fortement ta défense pendant un court moment.",
    effect: {
      buff: { statModifiers: { defensePercent: 0.7 }, durationMs: 30000 },
    },
    stackable: true,
    unlockLevel: 5,
    price: 55,
  },
  largeFortifyPotion: {
    id: "largeFortifyPotion",
    category: "consumable",
    name: "Grande potion de fortification",
    description: "Augmente fortement ta défense pendant un court moment.",
    effect: {
      buff: { statModifiers: { defensePercent: 0.9 }, durationMs: 40000 },
    },
    stackable: true,
    unlockLevel: 6,
    price: 70,
  },
  weaknessPotion: {
    id: "weaknessPotion",
    category: "consumable",
    name: "Fiole trouble",
    description: "Son effet est incertain...",
    effect: {
      buff: {
        statModifiers: { meleeDamagePercent: -0.3, rangedDamagePercent: -0.3 },
        durationMs: 15000,
      },
    },
    stackable: true,
    price: 5,
  },
  mediumWeaknessPotion: {
    id: "mediumWeaknessPotion",
    category: "consumable",
    name: "Moyenne fiole trouble",
    description: "Son effet est incertain...",
    effect: {
      buff: {
        statModifiers: { meleeDamagePercent: -0.5, rangedDamagePercent: -0.5 },
        durationMs: 20000,
      },
    },
    stackable: true,
    price: 10,
  },
  largeWeaknessPotion: {
    id: "largeWeaknessPotion",
    category: "consumable",
    name: "Grande fiole trouble",
    description: "Son effet est incertain...",
    effect: {
      buff: {
        statModifiers: { meleeDamagePercent: -0.7, rangedDamagePercent: -0.7 },
        durationMs: 25000,
      },
    },
    stackable: true,
    price: 15,
  },

  /** Objets explosifs */
  fireVial: {
    id: "fireVial",
    category: "consumable",
    name: "Fiole de feu",
    description: "Explose en une boule de feu au contact (20 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 15,
    effect: {
      combat: {
        effectType: "aoe",
        damage: 20,
        damageType: "fire",
        radius: 65,
        inflictsEffect: {
          type: "burn",
          kind: "dot",
          chance: 0.4,
          damagePerTick: 3,
          tickIntervalMs: 1000,
          ticks: 3,
        },
      },
    },
  },
  mediumFireVial: {
    id: "mediumFireVial",
    category: "consumable",
    name: "Fiole de feu moyenne",
    description: "Explose en une boule de feu au contact (30 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 25,
    effect: {
      combat: {
        effectType: "aoe",
        damage: 30,
        damageType: "fire",
        radius: 70,
        inflictsEffect: {
          type: "burn",
          kind: "dot",
          chance: 0.5,
          damagePerTick: 4,
          tickIntervalMs: 1000,
          ticks: 3,
        },
      },
    },
  },
  largeFireVial: {
    id: "largeFireVial",
    category: "consumable",
    name: "Grande fiole de feu",
    description: "Explose en une boule de feu au contact (40 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 35,
    effect: {
      combat: {
        effectType: "aoe",
        damage: 40,
        damageType: "fire",
        radius: 75,
        inflictsEffect: {
          type: "burn",
          kind: "dot",
          chance: 0.6,
          damagePerTick: 5,
          tickIntervalMs: 1000,
          ticks: 3,
        },
      },
    },
  },
  acidVial: {
    id: "acidVial",
    category: "consumable",
    name: "Fiole d'acide",
    description: "Libère un nuage toxique autour de toi (14 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 15,
    effect: {
      combat: {
        effectType: "aoe",
        damage: 14,
        damageType: "poison",
        radius: 60,
        inflictsEffect: {
          type: "acid",
          kind: "dot",
          chance: 0.6,
          damagePerTick: 4,
          tickIntervalMs: 1000,
          ticks: 3,
        },
      },
    },
  },
  mediumAcidVial: {
    id: "mediumAcidVial",
    category: "consumable",
    name: "Fiole d'acide moyenne",
    description: "Libère un nuage toxique autour de toi (20 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 25,
    effect: {
      combat: {
        effectType: "aoe",
        damage: 20,
        damageType: "poison",
        radius: 65,
        inflictsEffect: {
          type: "acid",
          kind: "dot",
          chance: 0.6,
          damagePerTick: 5,
          tickIntervalMs: 1000,
          ticks: 3,
        },
      },
    },
  },
  largeAcidVial: {
    id: "largeAcidVial",
    category: "consumable",
    name: "Grande fiole d'acide",
    description: "Libère un nuage toxique autour de toi (30 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 35,
    effect: {
      combat: {
        effectType: "aoe",
        damage: 30,
        damageType: "poison",
        radius: 70,
        inflictsEffect: {
          type: "acid",
          kind: "dot",
          chance: 0.6,
          damagePerTick: 6,
          tickIntervalMs: 1000,
          ticks: 3,
        },
      },
    },
  },
  stunBomb: {
    id: "stunBomb",
    category: "consumable",
    name: "Bombe étourdissante",
    description: "Étourdit tous les ennemis proches (10 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 18,
    effect: {
      combat: {
        effectType: "aoeStun",
        damage: 10,
        radius: 60,
        durationMs: 1500,
      },
    },
  },
  mediumStunBomb: {
    id: "mediumStunBomb",
    category: "consumable",
    name: "Bombe étourdissante moyenne",
    description: "Étourdit tous les ennemis proches (15 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 28,
    effect: {
      combat: {
        effectType: "aoeStun",
        damage: 15,
        radius: 65,
        durationMs: 2000,
      },
    },
  },
  largeStunBomb: {
    id: "largeStunBomb",
    category: "consumable",
    name: "Grande bombe étourdissante",
    description: "Étourdit tous les ennemis proches (20 dégâts).",
    stackable: true,
    unlockLevel: 1,
    price: 40,
    effect: {
      combat: {
        effectType: "aoeStun",
        damage: 20,
        radius: 70,
        durationMs: 2500,
      },
    },
  },

  leatherArmor: {
    id: "leatherArmor",
    category: "equipment",
    slot: "armor",
    name: "Armure de cuir",
    description: "+3 défense.",
    statBonus: { defense: 3 },
    stackable: false,
    unlockLevel: 1,
    price: 45,
  },

  vitalityCharm: {
    id: "vitalityCharm",
    category: "equipment",
    slot: "necklace",
    name: "Charme de vitalité",
    description: "+20 PV maximum.",
    statBonus: { maxHp: 20 },
    stackable: false,
    unlockLevel: 1,
    price: 70,
  },

  gold: {
    id: "gold",
    category: "currency",
    name: "Or",
    description: "Monnaie du jeu.",
    stackable: true,
  },

  //enchanted weapons with scroll

  reinforcedSword: {
    id: "reinforcedSword",
    category: "equipment",
    slot: "mainHand",
    twoHanded: false,
    grantsRanged: false,
    name: "Épée renforcée",
    description: "+2 dégât au corps à corps. Arme d'entraînement avancée.",
    statBonus: { meleeDamage: 2 },
    stackable: false,
    archetypes: ["guerrier"],
    price: 5,
    inflictsEffect: {
      type: "bleed",
      chance: 0.9,
      damagePerTick: 1,
      tickIntervalMs: 1000,
      ticks: 3,
    },
  },
  flamingSword: {
    id: "flamingSword",
    category: "equipment",
    slot: "mainHand",
    name: "Épée enflammée",
    description: "Une épée forgée dans les flammes.",
    statBonus: { meleeDamage: 5 }, // bonus de stat classique, deja utilise partout
    damageType: "fire", // type de degats (resistances elementaires)
    varianceDice: "1d6", // variance aleatoire sur les degats
    inflictsEffect: {
      // chance d'infliger un effet par coup - PAS de cooldown ici
      type: "burn",
      kind: "dot",
      chance: 0.3,
      damagePerTick: 3,
      tickIntervalMs: 1000,
      ticks: 3,
    },
    stackable: false,
  },

  //scroll
  fireballScroll: {
    id: "fireballScroll",
    category: "abilityScroll",
    name: "Parchemin : Boule de feu",
    description: "Apprend la compétence Boule de feu (consomme du mana).",
    grantsAbility: "fireball",
    stackable: true,
    unlockLevel: 1,
    price: 80,
  },
  whirlwindScroll: {
    id: "whirlwindScroll",
    category: "abilityScroll",
    name: "Parchemin : Tourbillon",
    description: "Apprend la compétence Tourbillon (consomme de la stamina).",
    grantsAbility: "whirlwind",
    stackable: true,
    unlockLevel: 1,
    price: 90,
  },
  hasteScroll: {
    id: "hasteScroll",
    category: "abilityScroll",
    name: "Parchemin : Hâte",
    description: "Apprend la compétence Hâte (consomme de la stamina).",
    grantsAbility: "haste",
    stackable: true,
    unlockLevel: 1,
    price: 85,
  },
  slowScroll: {
    id: "slowScroll",
    category: "abilityScroll",
    name: "Parchemin : Lenteur",
    description: "Apprend la compétence Lenteur (consomme du mana).",
    grantsAbility: "slow",
    stackable: true,
    unlockLevel: 1,
    price: 75,
  },
  flameWeaponScroll: {
    id: "flameWeaponScroll",
    category: "abilityScroll",
    name: "Parchemin : Lame enflammée",
    description:
      "Apprend la compétence Lame enflammée (consomme de la stamina).",
    grantsAbility: "flameWeapon",
    stackable: true,
    unlockLevel: 5,
    price: 95,
  },
  flamingEdgeScroll: {
    id: "flamingEdgeScroll",
    category: "abilityScroll",
    name: "Parchemin : Tranchant flamboyant",
    description: "Apprend l'enchantement Tranchant flamboyant.",
    grantsAbility: "flamingEdge",
    stackable: false,
    price: 45,
  },
  glacialEdgeScroll: {
    id: "glacialEdgeScroll",
    category: "abilityScroll",
    name: "Parchemin : Tranchant glacial",
    description: "Apprend l'enchantement Tranchant glacial.",
    grantsAbility: "glacialEdge",
    stackable: false,
    price: 45,
  },
  shockingEdgeScroll: {
    id: "shockingEdgeScroll",
    category: "abilityScroll",
    name: "Parchemin : Tranchant foudroyant",
    description: "Apprend l'enchantement Tranchant foudroyant.",
    grantsAbility: "shockingEdge",
    stackable: false,
    price: 45,
  },
  venomEdgeScroll: {
    id: "venomEdgeScroll",
    category: "abilityScroll",
    name: "Parchemin : Tranchant empoisonné",
    description: "Apprend l'enchantement Tranchant empoisonné.",
    grantsAbility: "venomEdge",
    stackable: false,
    price: 45,
  },
  holyEdgeScroll: {
    id: "holyEdgeScroll",
    category: "abilityScroll",
    name: "Parchemin : Tranchant sacré",
    description: "Apprend l'enchantement Tranchant sacré.",
    grantsAbility: "holyEdge",
    stackable: false,
    price: 45,
  },
  shadowEdgeScroll: {
    id: "shadowEdgeScroll",
    category: "abilityScroll",
    name: "Parchemin : Tranchant ténébreux",
    description: "Apprend l'enchantement Tranchant ténébreux.",
    grantsAbility: "shadowEdge",
    stackable: false,
    price: 45,
  },
  flameWallScroll: {
    id: "flameWallScroll",
    category: "abilityScroll",
    name: "Parchemin : Mur de flammes",
    description:
      "Apprend la compétence Mur de flammes (consomme de la stamina).",
    grantsAbility: "flameWall",
    stackable: true,
    unlockLevel: 5,
    price: 100,
  },
  detectTrapsScroll: {
    id: "detectTrapsScroll",
    category: "abilityScroll",
    name: "Parchemin : Détection de pièges",
    description: "Apprend la compétence Détection de pièges.",
    grantsAbility: "detectTraps",
    stackable: false,
    price: 40, // optionnel - retire ce champ si tu veux qu'il ne soit JAMAIS achetable en boutique (cf. getPurchasableItemIds, base uniquement sur la presence de price)
  },

  detectSecretsScroll: {
    id: "detectSecretsScroll",
    category: "abilityScroll",
    name: "Parchemin : Détection des secrets",
    description: "Apprend la compétence Détection des secrets.",
    grantsAbility: "detectSecrets",
    stackable: false,
    price: 45,
  },

  // recipes
  reinforcedSwordRecipe: {
    id: "reinforcedSwordRecipe",
    category: "recipeScroll",
    name: "Plan : Épée renforcée",
    description: "Apprend la recette de l'épée renforcée.",
    grantsRecipe: "reinforcedSwordRecipe",
    stackable: true,
    price: 60,
  },
  flamingSwordRecipe: {
    id: "flamingSwordRecipe",
    category: "recipeScroll",
    name: "Plan : Épée enflammée",
    description: "Apprend la recette de l'épée enflammée.",
    grantsRecipe: "flamingSwordRecipe",
    stackable: true,
    price: 70,
  },
  healthPotionRecipe: {
    id: "healthPotionRecipe",
    category: "recipeScroll",
    name: "Plan : Potion de soin",
    description: "Apprend la recette de la potion de soin.",
    grantsRecipe: "healthPotionRecipe",
    stackable: true,
    price: 50,
  },
  woodenArrowRecipe: {
    id: "woodenArrowRecipe",
    category: "recipeScroll",
    name: "Plan : Flèche en bois",
    description: "Apprend la recette de la flèche en bois.",
    grantsRecipe: "woodenArrowRecipe",
    stackable: true,
    price: 40,
  },
  bigWoodenArrowRecipe: {
    id: "bigWoodenArrowRecipe",
    category: "recipeScroll",
    name: "Plan : Flèche en bois géante",
    description: "Apprend la recette de la flèche en bois géante.",
    grantsRecipe: "bigWoodenArrowRecipe",
    stackable: true,
    price: 80,
  },

  // craft material
  deerAntler: {
    id: "deerAntler",
    category: "craftingMaterial",
    name: "Bois de cerf",
    description: "Un bois de cerf robuste, utilisé en artisanat.",
    stackable: true,
    price: 8,
  },
  mushroom: {
    id: "mushroom",
    category: "craftingMaterial",
    name: "Champignon",
    description: "Un champignon commun, utilisé en artisanat.",
    stackable: true,
    price: 5,
  },
  waterLily: {
    id: "waterLily",
    category: "craftingMaterial",
    name: "Nénuphar",
    description: "Une plante aquatique utilisée en artisanat.",
    stackable: true,
    price: 5,
  },
  ironOre: {
    id: "ironOre",
    category: "craftingMaterial",
    name: "Minerai de fer",
    description: "Un morceau de minerai brut, utilisé en artisanat.",
    stackable: true,
    price: 8,
  },
  silverOre: {
    id: "silverOre",
    category: "craftingMaterial",
    name: "Minerai d'argent",
    description: "Un morceau de minerai précieux, utilisé en artisanat.",
    stackable: true,
    price: 15,
  },
  goldOre: {
    id: "goldOre",
    category: "craftingMaterial",
    name: "Minerai d'or",
    description: "Un morceau de minerai rare, utilisé en artisanat.",
    stackable: true,
    price: 25,
  },
  ironIngot: {
    id: "ironIngot",
    category: "craftingMaterial",
    name: "Lingot de fer",
    description: "Un lingot de fer raffiné, utilisé en artisanat.",
    stackable: true,
    price: 15,
  },
  silverIngot: {
    id: "silverIngot",
    category: "craftingMaterial",
    name: "Lingot d'argent",
    description: "Un lingot d'argent raffiné, utilisé en artisanat.",
    stackable: true,
    price: 30,
  },
  goldIngot: {
    id: "goldIngot",
    category: "craftingMaterial",
    name: "Lingot d'or",
    description: "Un lingot d'or raffiné, utilisé en artisanat.",
    stackable: true,
    price: 50,
  },
  whetstone: {
    id: "whetstone",
    category: "craftingMaterial",
    name: "Pierre à aiguiser",
    description: "Une pierre utilisée pour aiguiser les lames.",
    stackable: true,
    price: 10,
  },
  foolsGold: {
    id: "foolsGold",
    category: "craftingMaterial",
    name: "Pyrite",
    description: "Un minéral trompeur ressemblant à de l'or.",
    stackable: true,
    price: 8,
  },
  moonStone: {
    id: "moonStone",
    category: "craftingMaterial",
    name: "Pierre de lune",
    description: "Une pierre précieuse avec une lueur mystérieuse.",
    stackable: true,
    price: 20,
  },
  diamond: {
    id: "diamond",
    category: "craftingMaterial",
    name: "Diamant",
    description: "Une pierre précieuse extrêmement dure et brillante.",
    stackable: true,
    price: 50,
  },
  smokyQuartz: {
    id: "smokyQuartz",
    category: "craftingMaterial",
    name: "Quartz fumé",
    description: "Un quartz avec une teinte fumée.",
    stackable: true,
    price: 10,
  },
  ruby: {
    id: "ruby",
    category: "craftingMaterial",
    name: "Rubis",
    description: "Une pierre précieuse rouge éclatante.",
    stackable: true,
    price: 50,
  },
  aquaMarine: {
    id: "aquaMarine",
    category: "craftingMaterial",
    name: "Aigue-marine",
    description: "Une pierre précieuse bleue claire.",
    stackable: true,
    price: 40,
  },
  peridot: {
    id: "peridot",
    category: "craftingMaterial",
    name: "Péridot",
    description: "Une pierre précieuse verte éclatante.",
    stackable: true,
    price: 30,
  },

  // exemple d'objet de quete - existe dans le monde, mais aucune quete
  // de type "en rapporter N" ne sait encore l'exploiter (cf. commentaire
  // en tete de fichier)
  ancientRelic: {
    id: "ancientRelic",
    category: "questItem",
    name: "Relique ancienne",
    description: "Un artefact qui semble important.",
    stackable: false,
  },
  redChest: {
    id: "redChest",
    category: "questItem",
    name: "Coffre rouge",
    description: "Un coffre verrouillé.",
    stackable: false,
  },
  greenApple: {
    id: "greenApple",
    category: "questItem",
    name: "Pomme verte",
    description: "Une pomme fraîche et juteuse.",
    stackable: false,
  },
  sealedPackage: {
    id: "sealedPackage",
    category: "questItem",
    name: "Colis scellé",
    description: "À livrer à son destinataire, sans l'ouvrir.",
    stackable: false,
  },
  orangeMushroom: {
    id: "orangeMushroom",
    category: "questItem",
    name: "Champignon orange",
    description: "Un champignon rare.",
    stackable: true,
    price: 5,
  },
};

/**
 * Résout la définition d'un objet, avec repli propre si le client ne
 * connaît pas encore une clé envoyée par le serveur (ex: nouvel objet
 * ajouté côté serveur avant que ce fichier soit mis à jour) - n'empêche
 * jamais l'objet d'exister dans l'inventaire, juste son affichage et ses
 * effets (repli sans statBonus/effect : l'objet ne fait juste rien de
 * spécial tant qu'il n'est pas correctement défini ici).
 */
export function resolveItemDef(itemId) {
  return (
    ITEM_DEFS[itemId] || {
      id: itemId,
      category: "unknown",
      name: itemId,
      description: "",
      stackable: true,
    }
  );
}
