/**
 * Miroir CLIENT des définitions d'objets - cf. server/services/generation/itemTypes.js,
 * la vraie source de vérité pour ce qui TOMBE (quel objet, où, à quelle
 * fréquence). `statBonus`/`effect`/`price` sont recopiés ici aussi
 * désormais (utilisés par equipment.js pour les bonus de stats, par
 * l'utilisation des consommables, et par la vente en boutique - cf.
 * MainScene.sellItem) - le serveur reste seul décideur de ce qui tombe,
 * mais une fois l'objet en inventaire, appliquer son effet ou calculer
 * son prix de revente est une opération purement locale, pas besoin
 * d'aller-retour serveur.
 *
 * Les deux fichiers doivent rester synchronisés à la main (mêmes clés,
 * mêmes statBonus/effect) - exactement la même discipline que
 * spriteRegistry.js (clés client) vs enemyStats.js/biomeConfig.js (clés
 * serveur) déjà en place ailleurs dans le projet.
 */
export const ITEM_DEFS = {
   woodenDagger: {
    id: 'woodenDagger',
    category: 'equipment',
    slot: 'mainHand', // une main - peut cohabiter avec un bouclier (offHand) ou une seconde arme (double armement automatique si offHand est libre, cf. MainScene.equipItem)
    twoHanded: false,
    grantsRanged: false, // explicite plutot qu'absent - purement melee, ne debloque jamais l'attaque a distance seule (cf. MainScene.canUseRangedAttack)
    name: 'Dague en bois',
    description: "+1 dégât au corps à corps et -2 à la distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: -2 },
    stackable: false,
    price: 2,
  },
  woodenSword: {
    id: 'woodenSword',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: false,
    grantsRanged: false,
    name: 'Épée en bois',
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    price: 2,
  },
  woodenBow: {
    id: 'woodenBow',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,  // occupe les DEUX mains - equiper libere mainHand ET offHand (cf. MainScene.equipItem)
    grantsRanged: true, // sans arme marquee ainsi equipee (ici ou en offHand), l'attaque a distance est indisponible - cf. MainScene.canUseRangedAttack
    requiresAmmo: ['woodenArrow'], // itemId EXACT requis (pas juste un booleen) - un carreau ne peut pas alimenter un arc, cf. MainScene.performRangedAttack
    name: 'Arc en bois',
    description: "+1 dégât à distance. Nécessite des flèches. Arme d'entraînement de départ.",
    statBonus: { rangedDamage: 1 },
    stackable: false,
    price: 2,
  },
  woodenCrossBow: {
    id: 'woodenCrossBow',
    category: 'equipement',
    slot: 'offHand',
    twoHanded: false',
    grantsRanged: true,
    requiresAmo: ['woodenCrossbowBolt'],
    name: 'Arbalète en bois',
    description: "+1 dégàt à distance, Nécessite des carreaux. +1 de distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { rangedDamage: 1, rangedRange: 1),
    stackable: false,
    price: 2,
  },    
  woodenSpear: {
    id: 'woodenSpear',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Lance en bois',
    description: "+1 dégât au corps à corps. +2 de distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: 2 },
    stackable: false,
    price: 2,
  },
  woodenAxe: {
    id: 'woodenAxe',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Hache de guerre en bois',
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    price: 2,
  },
  woodenMallet: {
    id: 'woodenMallet',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Masse en bois',
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    price: 2,
  },
  woodenShovel: {
    id: 'woodenShovel',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Pelle en bois',
    description: "+1 dégât au corps à corps. +1 de distance d'attaque. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: 1 },
    stackable: false,
    price: 2,
  },
  woodenPickaxe: {
    id: 'woodenPickaxe',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Pioche en bois',
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    price: 2,
  },
  woodenHammer: {
    id: 'woodenHammer',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Marteau de guerre en bois',
    description: "+1 dégât au corps à corps. Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1 },
    stackable: false,
    price: 2,
  },
  woodenSickle: {
    id: 'woodenSickle',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Faucille en bois',
    description: "+1 dégât au corps à corps. +1 de distance d'attaque  Arme d'entraînement de départ.",
    statBonus: { meleeDamage: 1, meleeRange: 1 },
    stackable: false,
    price: 2,
  },
  ironDagger: {
    id: 'ironDagger',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: false,
    grantsRanged: false, 
    name: 'Dague en fer',
    description: "+4 dégâts au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    price: 40,
  },
  ironSword: {
    id: 'ironSword',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: false,
    grantsRanged: false, 
    name: 'Épée de fer',
    description: "+5 dégâts au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    price: 60,
  },
  
  huntingBow: {
    id: 'huntingBow',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: true,
    requiresAmmo: ['woodenArrow', 'ironArrow'],
    name: 'Arc de chasse',
    description: "+4 dégâts à distance. +5 de distance d'attaque",
    statBonus: { rangedDamage: 4, rangedRange: 5 },
    stackable: false,
    price: 55,
  },
  crossbow: {
    id: 'crossbow',
    category: 'equipment',
    slot: 'mainHand', 
    twoHanded: false,
    grantsRanged: true,
    requiresAmmo: ['woodenCrossbowBolt', 'ironCrossbowBolt'],
    name: 'Arbalète',
    description: "+3 dégâts à distance. Se manie a une main.",
    statBonus: { rangedDamage: 3, rangedRange: 5 },
    stackable: false,
    price: 50,
  },
  ironSpear: {
    id: 'ironSpear',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Lance en fer',
    description: "+4 dégât au corps à corps. +3 de distance d'attaque.",
    statBonus: { meleeDamage: 4, meleeRange: 3 },
    stackable: false,
    price: 55,
  },
  ironAxe: {
    id: 'ironAxe',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Hache de guerre en fer',
    description: "+6 dégât au corps à corps.",
    statBonus: { meleeDamage: 6 },
    stackable: false,
    price: 65,
  },
  ironMallet: {
    id: 'ironMallet',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Masse en fer',
    description: "+5 dégât au corps à corps.",
    statBonus: { meleeDamage: 5 },
    stackable: false,
    price: 60,
  },
  ironShovel: {
    id: 'ironShovel',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Pelle en fer',
    description: "+4 dégât au corps à corps. +1 de distance d'attaque.",
    statBonus: { meleeDamage: 4, meleeRange: +1 },
    stackable: false,
    price: 55,
  },
  ironPickaxe: {
    id: 'ironPickaxe',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Pioche en fer',
    description: "+4 dégât au corps à corps.",
    statBonus: { meleeDamage: 4 },
    stackable: false,
    price: 50,
  },
  ironHammer: {
    id: 'ironHammer',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Marteau de guerre en fer',
    description: "+4 dégât au corps à corps.",
    statBonus: { meleeDamage: 4 },
    stackable: false,
    price: 50,
  },
  ironSickle: {
    id: 'ironSickle',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Faucille en fer',
    description: "+5 dégât au corps à corps. +2 de distance d'attaque.",
    statBonus: { meleeDamage: 5, meleeRange: 2 },
    stackable: false,
    price: 60,
  },
  bronzeDagger: {
    id: 'bronzeDagger',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: false,
    grantsRanged: false,
    name: 'Dague en bronze',
    description: '+10 dégâts au corps à corps.',
    statBonus: { meleeDamage: 10 },
    stackable: false,
    price: 100,
  },
  bronzeSword: {
    id: 'bronzeSword',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: false,
    grantsRanged: false, 
    name: 'Épée de bronze',
    description: "+12 dégâts au corps à corps. +2 de distance d'attaque.",
    statBonus: { meleeDamage: 12, meleeRange: +2 },
    stackable: false,
    price: 135,
  },  
  warBow: {
    id: 'warBow',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: true, 
    requiresAmmo: ['woodenArrow', 'ironArrow', 'acidArrow'], 
    name: 'Arc de guerre',
    description: "+10 dégâts à distance. +8 de distance d'attaque.",
    statBonus: { rangedDamage: 10, rangedRange: 8 },
    stackable: false,
    price: 140,
  },
  warCrossbow: {
    id: 'warCrossbow',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: false,
    grantsRanged: true,
    requiresAmmo: ['woodenCrossbowBolt', 'ironCrossbowBolt', 'acidCrossbowBolt'], 
    name: 'Arbalète',
    description: "+3 dégâts à distance. Se manie a une main.",
    statBonus: { rangedDamage: 6, rangedRange: 6 },
    stackable: false,
    price: 110,
  },
  bronzeSpear: {
    id: 'bronzeSpear',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Lance en bronze',
    description: "+8 dégât au corps à corps. +4 de distance d'attaque.",
    statBonus: { meleeDamage: 8, meleeRange: 4 },
    stackable: false,
    price: 125,
  },
  bronzeAxe: {
    id: 'bronzeAxe',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Hache de guerre en bronze',
    description: "+12 dégât au corps à corps.",
    statBonus: { meleeDamage: 12 },
    stackable: false,
    price: 130,
  },
  bronzeMallet: {
    id: 'bronzeMallet',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Masse en bronze',
    description: "+10 dégât au corps à corps.",
    statBonus: { meleeDamage: 10 },
    stackable: false,
    price: 125,
  },
  bronzeShovel: {
    id: 'bronzeShovel',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Pelle en bronze',
    description: "+8 dégât au corps à corps. +2 de distance d'attaque.",
    statBonus: { meleeDamage: 8, meleeRange: +2 },
    stackable: false,
    price: 120,
  },
  bronzePickaxe: {
    id: 'bronzePickaxe',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Pioche en bronze',
    description: "+8 dégât au corps à corps.",
    statBonus: { meleeDamage: 8 },
    stackable: false,
    price: 110,
  },
  bronzeHammer: {
    id: 'bronzeHammer',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Marteau de guerre en bronze',
    description: "+8 dégât au corps à corps.",
    statBonus: { meleeDamage: 8 },
    stackable: false,
    price: 110,
  },
  bronzeSickle: {
    id: 'bronzeSickle',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: false,
    name: 'Faucille en bronze',
    description: "+10 dégât au corps à corps. +3 de distance d'attaque.",
    statBonus: { meleeDamage: 10, meleeRange: 3 },
    stackable: false,
    price: 135,
  },
  woodenArrow: {
    id: 'woodenArrow',
    category: 'ammo',
    slot: 'quiver',
    name: 'Flèche en bois',
    description: '+1 dégât à distance tant que des flèches sont encochées.',
    statBonus: { rangedDamage: 1 },
    stackable: true,
    price: 1,
  },
  woodenCrossbowBolt: {
    id: 'woodenCrossbowBolt',
    category: 'ammo',
    slot: 'quiver',
    name: 'Carreau en bois',
    description: "+1 dégât à distance tant que des carreaux sont disponibles. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 1 },
    stackable: true,
    price: 1,
  },
  ironArrow: {
    id: 'ironArrow',
    category: 'ammo',
    slot: 'quiver',
    name: 'Flèche en fer',
    description: '+7 dégât à distance tant que des flèches sont encochées.',
    statBonus: { rangedDamage: 7 },
    stackable: true,
    price: 12,
  },
  ironCrossbowBolt: {
    id: 'ironCrossbowBolt',
    category: 'ammo',
    slot: 'quiver',
    name: 'Carreau de fer',
    description: "+5 dégât à distance tant que des carreaux sont encochés. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 5 },
    stackable: true,
    price: 10,
  },
  bronzeArrow: {
    id: 'bronzeArrow',
    category: 'ammo',
    slot: 'quiver',
    name: 'Flèche en bronze',
    description: '+15 dégât à distance tant que des flèches sont encochées.',
    statBonus: { rangedDamage: 15 },
    stackable: true,
    price: 35,
  },
  bronzeCrossbowBolt: {
    id: 'bronzeCrossbowBolt',
    category: 'ammo',
    slot: 'quiver',
    name: 'Carreau de bronze',
    description: "+12 dégât à distance et +2 de distance d'attaque tant que des carreaux sont encochés. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 12, rangedRange: 2 },
    stackable: true,
    price: 33,
  },
  acidArrow: {
    id: 'acidArrow',
    category: 'ammo',
    slot: 'quiver',
    name: "Flèche d'acide",
    description: '+15 dégât à distance tant que des flèches sont encochées.',
    statBonus: { rangedDamage: 15 },
    stackable: true,
    price: 45,
  },
  acidCrossbowBolt: {
    id: 'acidCrossbowBolt',
    category: 'ammo',
    slot: 'quiver',
    name: "Carreau d'acide",
    description: "+12 dégât à distance et +2 de distance d'attaque tant que des carreaux sont encochés. Munition de l'arbalète uniquement.",
    statBonus: { rangedDamage: 12, rangedRange: 2 },
    stackable: true,
    price: 43,
  },
  healthPotion: {
    id: 'healthPotion',
    category: 'consumable',
    name: 'petite potion de soin',
    description: "Restaure 30 PV à l'usage.",
    effect: { heal: 30 },
    stackable: true,
    price: 15, // vendable en boutique - cf. shopGenerator.js. Absent = jamais en vente (or, objets de quete)
  },
  mediumHealthPotion: {
    id: 'mediumHealthPotion',
    category: 'consumable',
    name: 'Moyenne potion de soin',
    description: "Restaure 60 PV à l'usage.",
    effect: { heal: 30 },
    stackable: true,
    price: 50,	
  },
   bigHealthPotion: {
    id: 'bigHealthPotion',
    category: 'consumable',
    name: 'Grande potion de soin',
    description: "Restaure 120 PV à l'usage.",
    effect: { heal: 120 },
    stackable: true,
    price: 200,	
  },
  manaPotion: {
    id: 'manaPotion',
    category: 'consumable',
    name: 'petite potion de mana',
    description: "Restaure 30 PM à l'usage.",
    effect: { mana: 10 },
    stackable: true,
    price: 12,
  },
  mediumManaPotion: {
    id: 'mediumManaPotion',
    category: 'consumable',
    name: 'Moyenne potion de mana',
    description: "Restaure 40 PM à l'usage.",
    effect: { mana: 40 },
    stackable: true,
    price: 45,	
  },
   bigManaPotion: {
    id: 'bigManaPotion',
    category: 'consumable',
    name: 'Grande potion de mana',
    description: "Restaure 80 PM à l'usage.",
    effect: { mana: 80 },
    stackable: true,
    price: 150,	
  },



  leatherArmor: {
    id: 'leatherArmor',
    category: 'equipment',
    slot: 'armor',
    name: 'Armure de cuir',
    description: '+3 défense.',
    statBonus: { defense: 3 },
    stackable: false,
    price: 45,
  },

  vitalityCharm: {
    id: 'vitalityCharm',
    category: 'equipment',
    slot: 'necklace',
    name: 'Charme de vitalité',
    description: '+20 PV maximum.',
    statBonus: { maxHp: 20 },
    stackable: false,
    price: 70,
  },

  gold: {
    id: 'gold',
    category: 'currency',
    name: 'Or',
    description: 'Monnaie du jeu.',
    stackable: true,
  },

  // exemple d'objet de quete - existe dans le monde, mais aucune quete
  // de type "en rapporter N" ne sait encore l'exploiter (cf. commentaire
  // en tete de fichier)
  ancientRelic: {
    id: 'ancientRelic',
    category: 'questItem',
    name: 'Relique ancienne',
    description: 'Un artefact qui semble important.',
    stackable: false,
  },

  woodenShield: {
    id: 'woodenShield',
    category: 'equipment',
    slot: 'offHand',
    twoHanded: false,
    grantsRanged: false,
    name: 'Bouclier en bois',
    description: "+1 défense. Équipement d'entraînement de départ.",
    statBonus: { defense: 1 },
    stackable: false,
  },


  woodenStaff: {
    id: 'woodenStaff',
    category: 'equipment',
    slot: 'mainHand',
    twoHanded: true,
    grantsRanged: true,
    requiresAmmo: false,
    manaCost: 1,
    name: 'Bâton en bois',
    description: "+1 dégât à distance. Canalise la magie (1 mana par tir), sans munitions. Arme d'entraînement de départ.",
    statBonus: { rangedDamage: 1 },
    stackable: false,
  },

  sealedPackage: {
    id: 'sealedPackage',
    category: 'questItem',
    name: 'Colis scellé',
    description: 'À livrer à son destinataire, sans l\'ouvrir.',
    stackable: false,
  },
}


/**
 * Résout la définition d'un objet, avec repli propre si le client ne
 * connaît pas encore une clé envoyée par le serveur (ex: nouvel objet
 * ajouté côté serveur avant que ce fichier soit mis à jour) - n'empêche
 * jamais l'objet d'exister dans l'inventaire, juste son affichage et ses
 * effets (repli sans statBonus/effect : l'objet ne fait juste rien de
 * spécial tant qu'il n'est pas correctement défini ici).
 */
export function resolveItemDef(itemId) {
  return (
    ITEM_DEFS[itemId] || {
      id: itemId,
      category: "unknown",
      name: itemId,
      description: "",
      stackable: true,
    }
  );
}
